import assert from 'node:assert/strict';import test from 'node:test';import {readFileSync} from 'node:fs';import ts from 'typescript';
import {verifyPhysicalIslandSuggestion} from '../lib/easyt/destination-resolution.ts';
import {searchReferencePlaces,referenceSnapshotId} from '../lib/easyt/place-reference.server.ts';
import {canonicalPlaceFactsMatch,isOvernightBaseEligible} from '../lib/easyt/place-intelligence.ts';
import {countryCodeFor} from '../lib/easyt/country-registry.ts';
import {canonicalRouteFixture} from './fixtures/batch14-route-documents.ts';
import {requireReadableTripDocument} from '../lib/easyt/trip-document.ts';
import type {CanonicalPlaceSuggestion,PlanningParentConstraint} from '../lib/easyt/place-intelligence.ts';
const source=readFileSync(new URL('../app/journey/new/trip-builder.tsx',import.meta.url),'utf8');
const fira=searchReferencePlaces('Fira',{explicitCountryNames:['Greece']}).find(c=>c.canonicalPlaceId==='reference:geonames:252920')!;
const parent:PlanningParentConstraint={canonicalName:'Santorini',canonicalPlaceId:'santorini',placeType:'island',parentCountries:['Greece'],bounds:{south:36.3,west:25.3,north:36.5,east:25.6}};
const chosen:CanonicalPlaceSuggestion={canonicalPlaceId:fira.canonicalPlaceId!,name:fira.canonicalName,label:'Firá, Greece',country:'Greece',region:'Santorini',placeType:'city',routability:'direct_destination',coordinates:fira.coordinates,referenceSnapshotId:referenceSnapshotId(),provenance:[{id:fira.providerId,label:'GeoNames',kind:'provider',supports:'Original settlement index'}]};
const proof='Physical island verified: OSM relation:453964; timestamp=2026-10-10T03:55:36Z; point=25.43087,36.42107; country=GR; result=strict-inside/outside-holes; name=Santorini';
function verified(){return {canonicalPlaceId:chosen.canonicalPlaceId,providerId:fira.providerId,country:'Greece',coordinates:chosen.coordinates,region:'Santorini',normalizationReason:proof,placeType:'city',routability:'direct_destination'};}
test('local catalog/name/bounds proposal cannot bypass server physical containment',async()=>{let queries=0;const result=await verifyPhysicalIslandSuggestion(parent,chosen,{fetchImpl:async input=>{queries++;const q=new URL(String(input),'http://localhost');assert.equal(q.searchParams.get('parentType'),'island');assert.equal(q.searchParams.get('parentName'),'Santorini');return Response.json({candidates:[]});}});assert.equal(queries,1);assert.equal(result,null);});
test('verification preserves exact chosen identity/point and records complete existing provenance support',async()=>{const before=structuredClone(chosen),result=await verifyPhysicalIslandSuggestion(parent,chosen,{fetchImpl:async()=>Response.json({candidates:[verified()]})});assert(result);assert.equal(result.canonicalPlaceId,chosen.canonicalPlaceId);assert.deepEqual(result.coordinates,chosen.coordinates);assert.equal(result.provenance[0].id,fira.providerId);assert.equal(result.provenance[0].supports,proof);assert.deepEqual(chosen,before);});
test('server response cannot silently substitute a different identity/point/country/type or incomplete proof',async()=>{for(const change of [(c:any)=>c.providerId='different-provider',(c:any)=>c.canonicalPlaceId='different-city',(c:any)=>c.coordinates=[25.43,36.42],(c:any)=>c.country='Italy',(c:any)=>c.placeType='transport_gateway',(c:any)=>c.normalizationReason=undefined,(c:any)=>c.region='Thira Municipal Unit']){const c=verified();change(c);assert.equal(await verifyPhysicalIslandSuggestion(parent,chosen,{fetchImpl:async()=>Response.json({candidates:[c]})}),null);}});
function actualAdd(scope:Record<string,unknown>){const code=source.slice(source.indexOf('  const addStop = async ('),source.indexOf('  const addSupportedBase ='));const js=ts.transpileModule(`return (()=>{${code};return addStop;})();`,{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText;return new Function('scope',`with(scope){${js}}`)(scope);}
for(const stale of [false,true])test(`mounted Builder discovery-verified island choice still checks physical proof${stale?' and ignores a stale result':''}`,async()=>{
 const trip=requireReadableTripDocument(canonicalRouteFixture()),before=structuredClone(trip),intent=trip.brief.intent.route.destinations[0]!;let snapshot={trip,browserOwnerId:'owner-a',inputRevision:1},checks=0,dispatches=0;const errors:string[]=[];let finish:(value:any)=>void=()=>{};
 const mention={mentionId:intent.id,canonicalName:'Santorini',sourceText:'Santorini',placeType:'island',routability:'direct_destination',requiresBaseSelection:true,parentCountries:['Greece']};
 const pending=new Promise(resolve=>finish=resolve);
 const scope:any={builderEditSessionRef:{current:{getSnapshot:()=>snapshot}},activeBrowserOwnerIdRef:{current:'owner-a'},addPlaceLookupSequenceRef:{current:0},countryAddReviewRef:{current:null},resolvingPlaceMentionId:null,capturedStructuredBrief:{placeMentions:[mention]},intakeMentions:[],stops:trip.stops,stopInput:'Fira',setBaseSearchErrors:(update:any)=>{const next=update({});if(next[intent.id])errors.push(next[intent.id]);},setStopChecking:()=>{},language:'en',ui:{unavailable:'unavailable'},isOvernightBaseEligible,canonicalPlaceFactsMatch,countryCodeFor,planningParentForMention:()=>parent,placeDisplayName:()=> 'Santorini',verifyPhysicalIslandSuggestion:async()=>{checks++;return pending;},dispatchAcceptedBuilderEdits:()=>{dispatches++;return true;}};
 const action=actualAdd(scope)(chosen.name,chosen.country,intent.id,undefined,chosen,true);assert.equal(checks,1,'A previously discovery-verified/catalog label is not independent physical proof');if(stale)snapshot={...snapshot,inputRevision:2};finish(stale?chosen:null);await action;assert.equal(dispatches,0);assert.deepEqual(trip,before);if(!stale)assert(errors.some(e=>e.includes('independently verify')));else assert.equal(errors.length,0);
});
test('mounted autocomplete forwards physical normalization into existing provider choice provenance',()=>{const text=readFileSync(new URL('../components/easyt/canonical-place-autocomplete.tsx',import.meta.url),'utf8');const start=text.indexOf('          const nextSuggestions =');const end=text.indexOf('          scope.commit(() => setProviderSuggestions(nextSuggestions));',start);const code=text.slice(start,end);const js=ts.transpileModule(`return (()=>{${code};return nextSuggestions;})();`,{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText;const result=new Function('scope',`with(scope){${js}}`)({payload:{candidates:[{...verified(),name:chosen.name,kind:'city',referenceSnapshotId:referenceSnapshotId()}]},referenceGeographicAcceptanceMatches:()=>true,allowedPlaceTypes:['city','town'],nearbyAnchor:undefined});assert.equal(result[0].provenance[0].supports,proof);assert.equal(result[0].provenance[0].id,fira.providerId);});

test('the exact saved selection expression keeps fresh physical proof ahead of earlier selection draft',()=>{const start=source.indexOf('provenance: (targetMention?.placeType === "island" ?');assert(start>=0);const end=source.indexOf(',\n',start);const expression=source.slice(start+'provenance: '.length,end);const result=new Function('targetMention','canonicalSuggestion','selectionDraft','targetMentionId','id',`return (${expression});`)({placeType:'island'},{provenance:[{id:fira.providerId,supports:proof}]},{provenance:{id:'draft',supports:'Earlier proposal'}},'santorini','santorini-2');assert.equal(result.supports,proof);});
test('mounted supported island base callback delegates to the guarded acceptance handler',()=>{const start=source.indexOf('  const addSupportedBase =');const end=source.indexOf('    const optionCountry =',start);const code=source.slice(start,end)+'};return addSupportedBase;';const js=ts.transpileModule(code,{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText;let calls=0;const fn=new Function('scope',`with(scope){${js}}`)({activeCapturedPlaceMentions:[{mentionId:'source',placeType:'island'}],isOriginMention:()=>false,addStop:(name:string,country:string,id:string,_draft:any,suggestion:any)=>{calls++;assert.equal(id,'source');assert.equal(suggestion.canonicalPlaceId,chosen.canonicalPlaceId);assert.deepEqual(suggestion.coordinates,chosen.coordinates);}});fn({mentionId:'source'},{label:chosen.name,country:chosen.country,canonicalPlaceId:chosen.canonicalPlaceId,coordinates:chosen.coordinates,placeType:'city',provenance:chosen.provenance});assert.equal(calls,1);});
test('mounted island provider clarification delegates origin and destination to guarded handlers',async()=>{const start=source.indexOf('  const chooseProviderClarification =');const end=source.indexOf('    if(builderEditSessionRef.current) {',start);const js=ts.transpileModule(source.slice(start,end)+'};return chooseProviderClarification;', {compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText;for(const origin of [false,true]){let baseChecks=0,cleanup=0;const snapshot={trip:{id:'trip'},browserOwnerId:'owner',inputRevision:1};const scope:any={builderEditSessionRef:{current:{getSnapshot:()=>snapshot}},providerClarificationScope:{tripId:'trip',ownerId:'owner',revision:1,mentionId:'source'},activeBrowserOwnerIdRef:{current:'owner'},isOriginMention:()=>origin,addStop:async()=>{baseChecks++;return false;},selectOriginBase:async()=>{baseChecks++;return false;},setLocationChoices:()=>cleanup++,advanceClarificationSession:()=>cleanup++};const fn=new Function('scope',`with(scope){${js}}`)(scope);await fn({mentionId:'source',placeType:'island'},{name:chosen.name,country:chosen.country,canonicalPlaceId:chosen.canonicalPlaceId,providerId:fira.providerId,coordinates:chosen.coordinates,placeType:'city'});assert.equal(baseChecks,1);assert.equal(cleanup,0);snapshot.inputRevision=2;await fn({mentionId:'source',placeType:'island'},{name:chosen.name,country:chosen.country,coordinates:chosen.coordinates,placeType:'city'});assert.equal(baseChecks,1);}});

test('supported island origin base delegates to the guarded origin handler',()=>{const start=source.indexOf('  const addSupportedBase ='),end=source.indexOf('    const optionCountry =',start);const js=ts.transpileModule(source.slice(start,end)+'};return addSupportedBase;', {compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText;let checks=0;const fn=new Function('scope',`with(scope){${js}}`)({activeCapturedPlaceMentions:[{mentionId:'source',placeType:'island'}],isOriginMention:()=>true,selectOriginBase:(mention:any,suggestion:any)=>{checks++;assert.equal(mention.mentionId,'source');assert.equal(suggestion.canonicalPlaceId,chosen.canonicalPlaceId);},addStop:()=>{throw Error('Origin cannot create a destination stop');}});fn({mentionId:'source'},{label:chosen.name,country:chosen.country,canonicalPlaceId:chosen.canonicalPlaceId,coordinates:chosen.coordinates,placeType:'city',provenance:chosen.provenance});assert.equal(checks,1);});
