import assert from 'node:assert/strict';
import test from 'node:test';
import {readFileSync} from 'node:fs';
import {searchReferencePlaces} from '../lib/easyt/place-reference.server.ts';
import {normalizePhysicalIslandBaseCandidates} from '../lib/easyt/openstreetmap-island-containment.server.ts';
import type {PlaceProviderCandidate,PlanningParentConstraint} from '../lib/easyt/place-intelligence.ts';
const raw=JSON.parse(readFileSync(new URL('./fixtures/batch14-physical-island-geography.json',import.meta.url),'utf8'));
const fira=searchReferencePlaces('Fira',{explicitCountryNames:['Greece']}).find(c=>c.canonicalPlaceId==='reference:geonames:252920')!;
const parent:PlanningParentConstraint={canonicalPlaceId:'santorini',canonicalName:'Santorini',placeType:'island',parentCountries:['Greece']};
function fixture(photon=raw.photon.body,geometry=raw.overpass.body):typeof fetch{return async(input,init)=>{const url=String(input);if(url.startsWith('https://photon.komoot.io/api/'))return Response.json(photon);assert(['https://overpass-api.de/api/interpreter','https://overpass.kumi.systems/api/interpreter'].includes(url));assert.equal(init?.method,'POST');assert.match(String(init?.body),/453964/);return Response.json(geometry);};}
async function resolve(candidates:PlaceProviderCandidate[]= [fira],p=parent,fetchImpl=fixture()){return normalizePhysicalIslandBaseCandidates(candidates,p,{fetchImpl});}
test('recorded physical island polygon confirms the unchanged real reference settlement with exact provenance',async()=>{const before=structuredClone(fira);const [c]=await resolve();assert(c);assert.equal(c.canonicalPlaceId,fira.canonicalPlaceId);assert.equal(c.providerId,fira.providerId);assert.deepEqual(c.coordinates,fira.coordinates);assert.equal(c.parentRegionId,'Santorini');assert.match(c.normalizationReason!,/relation:453964/);assert.match(c.normalizationReason!,/2026-10-10T03:55:36Z/);assert.match(c.normalizationReason!,/25\.43087/);assert.deepEqual(fira,before);});
test('sibling island and water inside the parent bounding rectangle are rejected without bounds fallback',async()=>{for(const coordinates of [[25.3361087,36.4339362],[25.36,36.4]] as [number,number][])assert.deepEqual(await resolve([{...fira,coordinates,parentRegionId:'Santorini'}],{...parent,bounds:{south:36.3321735,west:25.3538553,north:36.482206,east:25.4878919}}),[]);});
test('city on a different country, airport, area, missing point and non-routable candidates cannot become bases',async()=>{for(const c of [{...fira,parentCountries:['Italy']},{...fira,placeType:'transport_gateway' as const},{...fira,placeType:'island' as const},{...fira,coordinates:undefined},{...fira,routability:'planning_area' as const}])assert.deepEqual(await resolve([c]),[]);});
test('municipal administrative, archipelago and ambiguous same-name island search facts do not certify containment',async()=>{const actual=raw.photon.body.features.find((x:any)=>x.properties.osm_id===453964);for(const features of [[{...actual,properties:{...actual.properties,osm_key:'boundary',osm_value:'administrative'}}],[{...actual,properties:{...actual.properties,osm_value:'archipelago'}}],[actual,{...actual,properties:{...actual.properties,osm_id:999999}}]])assert.deepEqual(await resolve([fira],parent,fixture({features})),[]);});
test('physical geometry must independently match actual returned OSM identity/name/taxonomy',async()=>{for(const change of [(e:any)=>e.id=999999,(e:any)=>e.tags['name:en']='Different island',(e:any)=>e.tags.boundary='administrative',(e:any)=>e.tags.place='archipelago',(e:any)=>e.tags.type='boundary',(e:any)=>e.tags.country='Italy']){const geometry=structuredClone(raw.overpass.body);change(geometry.elements[0]);assert.deepEqual(await resolve([fira],parent,fixture(raw.photon.body,geometry)),[]);}});
test('open or malformed way fragments and invalid coordinate data fail closed',async()=>{for(const change of [(e:any)=>e.members.pop(),(e:any)=>e.members[0].geometry[0].lat=100,(e:any)=>e.members[0].geometry[0].lon='25',(e:any)=>e.members[0].geometry=undefined,(e:any)=>e.members[0].role='unknown',(e:any)=>e.members[0].geometry.push({lat:36.2,lon:180})]){const geometry=structuredClone(raw.overpass.body);change(geometry.elements[0]);assert.deepEqual(await resolve([fira],parent,fixture(raw.photon.body,geometry)),[]);}});
test('settlement exactly on a physical island polygon boundary is not accepted',async()=>{const point=raw.overpass.body.elements[0].members[0].geometry[0];assert.deepEqual(await resolve([{...fira,coordinates:[point.lon,point.lat]}]),[]);});
function square(west:number,south:number,east:number,north:number){return [{lon:west,lat:south},{lon:east,lat:south},{lon:east,lat:north},{lon:west,lat:north},{lon:west,lat:south}];}
test('inner holes and self-crossing rings are rejected independently of rectangle membership',async()=>{const geometry=structuredClone(raw.overpass.body);geometry.elements[0].members=[{type:'way',ref:1,role:'outer',geometry:square(25,36,26,37)},{type:'way',ref:2,role:'inner',geometry:square(25.4,36.4,25.5,36.5)}];assert.deepEqual(await resolve([fira],parent,fixture(raw.photon.body,geometry)),[]);geometry.elements[0].members=[{type:'way',ref:1,role:'outer',geometry:[{lon:25,lat:36},{lon:26,lat:37},{lon:25,lat:37},{lon:26,lat:36},{lon:25,lat:36}]}];assert.deepEqual(await resolve([fira],parent,fixture(raw.photon.body,geometry)),[]);});
test('generic physical-island verification does not depend on the captured island name or provider ID',async()=>{const photon=structuredClone(raw.photon.body),geometry=structuredClone(raw.overpass.body);photon.features=photon.features.filter((x:any)=>x.properties.osm_id===453964);photon.features[0].properties.name='Synthetic Test Island';photon.features[0].properties.osm_id=123456;geometry.elements[0].id=123456;geometry.elements[0].tags['name:en']='Synthetic Test Island';geometry.elements[0].tags.int_name='Synthetic Test Island';const fetchImpl:typeof fetch=async(input,init)=>String(input).startsWith('https://photon.komoot.io/api/')?Response.json(photon):(assert.match(String(init?.body),/123456/),Response.json(geometry));const [c]=await resolve([fira],{...parent,canonicalName:'Synthetic Test Island',canonicalPlaceId:'synthetic-test-island'},fetchImpl);assert(c);assert.equal(c.parentRegionId,'Synthetic Test Island');assert.match(c.normalizationReason!,/relation:123456/);});
test('existing non-island parent path does not require new provider requests',async()=>{const p={...parent,placeType:'country' as const};assert.deepEqual(await resolve([fira],p,async()=>{throw Error('Unexpected fetch');}),[fira]);});
test('unavailable existing geometry providers produce a recoverable failure rather than false containment',async()=>{const fetchImpl:typeof fetch=async(input)=>String(input).startsWith('https://photon.komoot.io/api/')?Response.json(raw.photon.body):new Response('',{status:503});await assert.rejects(resolve([fira],parent,fetchImpl),/unavailable/i);});
test('holes outside the island or crossing each other, duplicate paths and zero-area rings are rejected',async()=>{const bodies=[
 [{type:'way',ref:1,role:'outer',geometry:square(25,36,26,37)},{type:'way',ref:2,role:'inner',geometry:square(26,37,27,38)}],
 [{type:'way',ref:1,role:'outer',geometry:square(25,36,26,37)},{type:'way',ref:2,role:'inner',geometry:square(25.1,36.1,25.3,36.3)},{type:'way',ref:3,role:'inner',geometry:square(25.2,36.2,25.4,36.4)}],
 [{type:'way',ref:1,role:'outer',geometry:square(25,36,26,37)},{type:'way',ref:2,role:'outer',geometry:square(25,36,26,37)}],
 [{type:'way',ref:1,role:'outer',geometry:[{lon:25,lat:36},{lon:26,lat:37},{lon:25.5,lat:36.5},{lon:25,lat:36}]}],
 ];for(const members of bodies){const geometry=structuredClone(raw.overpass.body);geometry.elements[0].members=members;assert.deepEqual(await resolve([fira],parent,fixture(raw.photon.body,geometry)),[]);}});
test('combined point and response body limits fail closed',async()=>{const geometry=structuredClone(raw.overpass.body);geometry.elements[0].members.push(...structuredClone(geometry.elements[0].members));assert.deepEqual(await resolve([fira],parent,fixture(raw.photon.body,geometry)),[]);const huge={...raw.overpass.body,padding:'x'.repeat(4000000)};await assert.rejects(resolve([fira],parent,fixture(raw.photon.body,huge)),/unavailable/i);});
test('essential physical proof survives the existing240char normalization boundary even with a long island name',async()=>{const name='Synthetic physical island '+ 'a'.repeat(120),photon=structuredClone(raw.photon.body),geometry=structuredClone(raw.overpass.body);photon.features=photon.features.filter((x:any)=>x.properties.osm_id===453964);photon.features[0].properties.name=name;geometry.elements[0].tags['name:en']=name;const [c]=await resolve([fira],{...parent,canonicalName:name},fixture(photon,geometry));assert(c);assert(c.normalizationReason!.length<=240);for(const fact of ['relation:453964','2026-10-10T03:55:36Z','25.43087,36.42107','country=GR','strict-inside/outside-holes'])assert(c.normalizationReason!.includes(fact),fact);});
test('the existing-provider geometry timeout aborts instead of leaving an unbounded pending result',async()=>{const fetchImpl:typeof fetch=async(input,init)=>String(input).startsWith('https://photon.komoot.io/api/')?Response.json(raw.photon.body):new Promise((_resolve,reject)=>{const signal=init?.signal;assert(signal);if(signal.aborted)reject(signal.reason);else signal.addEventListener('abort',()=>reject(signal.reason),{once:true});});const started=Date.now();await assert.rejects(resolve([fira],parent,fetchImpl),/unavailable/i);assert(Date.now()-started<11500);});

test('captured larger physical Crete polygon accepts the existing unchanged Chaniá settlement',async()=>{const captured=JSON.parse(readFileSync(new URL('./fixtures/batch14-physical-crete-geography.json',import.meta.url),'utf8'));const chania=searchReferencePlaces('Chania',{explicitCountryNames:['Greece']}).find(c=>c.canonicalName.toLowerCase().includes('chani'))!;assert(chania);const fetchImpl:typeof fetch=async input=>String(input).startsWith('https://photon.komoot.io/api/')?Response.json(captured.photon.body):Response.json(captured.overpass.body);const candidates=await resolve([chania],{canonicalName:'Crete',placeType:'island',parentCountries:['Greece']},fetchImpl);assert.equal(candidates.length,1,'Initial polygon limits reject an existing required Chaniá choice');assert.equal(candidates[0].canonicalPlaceId,chania.canonicalPlaceId);assert.deepEqual(candidates[0].coordinates,chania.coordinates);assert.match(candidates[0].normalizationReason!,/relation:453129/);});

test('bounded dense simple geometry is rejected without approximating or skipping topology checks',async()=>{const geometry=structuredClone(raw.overpass.body),points:Array<{lon:number;lat:number}>=[];for(let i=0;i<5000;i++){points.push({lon:i%2?26:25,lat:36+i/10000},{lon:i%2?25:26,lat:36+i/10000});}points.push({lon:24.9,lat:36.4999},{lon:24.9,lat:36},{...points[0]!});geometry.elements[0].members=[{type:'way',ref:1,role:'outer',geometry:points}];const start=Date.now();assert.deepEqual(await resolve([fira],parent,fixture(raw.photon.body,geometry)),[]);assert(Date.now()-start<5000);});
test('point/member caps and adjacent overlapping edges fail closed',async()=>{for(const members of [[{type:'way',ref:1,role:'outer',geometry:Array.from({length:60001},(_,i)=>({lon:25+i/100000,lat:36}))}],Array.from({length:601},(_,i)=>({type:'way',ref:i,role:'outer',geometry:square(25,36,26,37)})),[{type:'way',ref:1,role:'outer',geometry:[{lon:25,lat:36},{lon:26,lat:36},{lon:25.5,lat:36},{lon:26,lat:37},{lon:25,lat:37},{lon:25,lat:36}]}]]){const geometry=structuredClone(raw.overpass.body);geometry.elements[0].members=members;assert.deepEqual(await resolve([fira],parent,fixture(raw.photon.body,geometry)),[]);}});
