import assert from "node:assert/strict";
import test from "node:test";
import { generateRouteCandidates } from "../lib/easyt/route-candidates.ts";
import { analyzeRouteCountryContinuity } from "../lib/easyt/route-country-continuity.ts";
import type { EstimatedLeg, PlannerStop } from "../lib/easyt/planner.ts";

const stop = (id: string, longitude: number): PlannerStop => ({ id, name: id, country: "Testland", coordinates: [longitude, 0] });
const countryStop = (id: string, countryCode: string | undefined, longitude: number, canonicalPlaceId = id): PlannerStop => ({
  id,
  name: id,
  country: countryCode ?? "Unknown",
  ...(countryCode ? { countryCode } : {}),
  canonicalPlaceId,
  coordinates: [longitude, 0],
});
const origin = { name: "Origin", coordinates: [-1, 0] as [number, number] };
const estimatedLeg = (from: { coordinates?: [number, number] }, to: PlannerStop): EstimatedLeg => {
  const distanceKm = Math.abs((to.coordinates?.[0] ?? 0) - (from.coordinates?.[0] ?? 0)) * 100;
  return { mode: "train", distanceKm, durationMinutes: distanceKm, label: "Test connection", note: "Planning estimate.", confidence: "medium" };
};

test("every candidate preserves fixed start and end", () => {
  const stops = [stop("bangkok", 0), stop("siem-reap", 1), stop("phnom-penh", 2), stop("hcmc", 3)];
  const result = generateRouteCandidates({ origin, stops, constraints: { fixedStartStopId: "bangkok", fixedEndStopId: "hcmc" }, estimateLeg: estimatedLeg });
  assert.ok(result.candidates.length > 0);
  assert.equal(result.candidates.every((candidate) => candidate.stops[0]?.id === "bangkok" && candidate.stops.at(-1)?.id === "hcmc"), true);
});

test("required destinations remain in every candidate", () => {
  const stops = [stop("a", 0), stop("anchor", 1), stop("b", 2)];
  const result = generateRouteCandidates({ origin, stops, constraints: { requiredStopIds: ["anchor"] }, estimateLeg: estimatedLeg });
  assert.equal(result.candidates.every((candidate) => candidate.stops.some((item) => item.id === "anchor")), true);
});

test("fixed endpoints only permute flexible middle stops", () => {
  const stops = [stop("bangkok", 0), stop("siem-reap", 1), stop("phnom-penh", 2), stop("hcmc", 3)];
  const result = generateRouteCandidates({ origin, stops, constraints: { fixedStartStopId: "bangkok", fixedEndStopId: "hcmc" }, estimateLeg: estimatedLeg });
  assert.deepEqual(result.candidates.map((candidate) => candidate.stops.map((item) => item.id)), [
    ["bangkok", "siem-reap", "phnom-penh", "hcmc"],
    ["bangkok", "phnom-penh", "siem-reap", "hcmc"],
  ]);
});

test("a genuinely identical fixed first and last active stop remains a hard conflict", () => {
  const stops = [stop("boundary", 0), stop("middle", 1)];
  const result = generateRouteCandidates({
    origin,
    stops,
    constraints: { fixedStartStopId: "boundary", fixedEndStopId: "boundary" },
    estimateLeg: estimatedLeg,
  });
  assert.equal(result.candidates.length, 0);
  assert.deepEqual(result.constraintIssues.find((issue) => issue.code === "fixed-endpoint-conflict")?.stopIds, ["boundary"]);
});

test("the original route remains a candidate when hard constraints allow it", () => {
  const stops = [stop("c", 2), stop("a", 0), stop("b", 1)];
  const result = generateRouteCandidates({ origin, stops, estimateLeg: estimatedLeg });
  const original = result.candidates.find((candidate) => candidate.metadata.matchesOriginalOrder);
  assert.deepEqual(original?.stops.map((item) => item.id), ["c", "a", "b"]);
  assert.equal(original?.source, "existing");
});

test("unlinked fixed commitments conservatively protect the entered order", () => {
  const stops = [stop("c", 2), stop("a", 0), stop("b", 1)];
  const result = generateRouteCandidates({ origin, stops, constraints: { fixedCommitments: [{ label: "Wedding", date: "2026-09-10" }] }, estimateLeg: estimatedLeg });
  assert.equal(result.candidates.length, 1);
  assert.deepEqual(result.candidates[0]?.stops.map((item) => item.id), ["c", "a", "b"]);
  assert.equal(result.candidates[0]?.source, "existing");
});

test("candidate orders generated by multiple paths are deduplicated by stop ID", () => {
  const stops = Array.from({ length: 7 }, (_, index) => stop(`stop-${index}`, index));
  const result = generateRouteCandidates({ origin, stops, estimateLeg: estimatedLeg });
  const keys = result.candidates.map((candidate) => candidate.stops.map((item) => item.id).join("|"));
  assert.equal(new Set(keys).size, keys.length);
  assert.ok(result.rawCandidateCount >= result.candidates.length);
});

test("seven and fifteen stop routes use bounded candidate generation", () => {
  for (const count of [7, 15]) {
    const result = generateRouteCandidates({ origin, stops: Array.from({ length: count }, (_, index) => stop(`stop-${index}`, index)), estimateLeg: estimatedLeg });
    assert.equal(result.strategy, "bounded");
    assert.ok(result.candidates.length >= 5);
    assert.ok(result.candidates.length <= 20);
    assert.equal(result.truncated, true);
  }
});

test("hard transport conflicts prune while soft preferences do not", () => {
  const stops = [stop("a", 0), stop("b", 1)];
  const roadLeg = (from: { coordinates?: [number, number] }, to: PlannerStop): EstimatedLeg => ({ ...estimatedLeg(from, to), mode: "road", confidence: "high" });
  const hard = generateRouteCandidates({ origin, stops, constraints: { avoidDriving: true }, estimateLeg: roadLeg });
  assert.equal(hard.candidates.length, 0);
  assert.equal(hard.constraintIssues.some((issue) => issue.code === "forbidden-transport-mode"), true);

  const soft = generateRouteCandidates({ origin, stops, constraints: { transportModes: ["train"] }, estimateLeg: roadLeg });
  assert.ok(soft.candidates.length > 0);

  const heuristicRoadLeg = (from: { coordinates?: [number, number] }, to: PlannerStop): EstimatedLeg => ({ ...roadLeg(from, to), confidence: "medium" });
  const heuristicHard = generateRouteCandidates({ origin, stops, constraints: { avoidDriving: true }, estimateLeg: heuristicRoadLeg });
  assert.equal(heuristicHard.candidates.length, 0);
  assert.equal(heuristicHard.constraintIssues.some((issue) => issue.code === "forbidden-transport-mode"), true);
});

test("a required-stop maximum contradiction returns a structured issue without dropping an anchor", () => {
  const stops = [stop("a", 0), stop("b", 1), stop("c", 2)];
  const result = generateRouteCandidates({
    origin,
    stops,
    constraints: { requiredStopIds: ["a", "b", "c"], maximumStops: 2 },
    estimateLeg: estimatedLeg,
  });
  assert.equal(result.candidates.length, 0);
  assert.equal(result.constraintIssues.some((issue) => issue.code === "required-stops-exceed-maximum"), true);
  assert.equal(result.constraintIssues.some((issue) => issue.code === "maximum-stops-exceeded"), true);
});

test("a maximum transfer ceiling rejects every violating candidate before scoring", () => {
  const stops = [stop("a", 0), stop("b", 1), stop("c", 2)];
  const threeHours = (from: { coordinates?: [number, number] }, to: PlannerStop): EstimatedLeg => ({
    ...estimatedLeg(from, to),
    durationMinutes: 180,
  });
  const result = generateRouteCandidates({
    origin,
    stops,
    constraints: { maximumTransferMinutes: 120 },
    estimateLeg: threeHours,
  });

  assert.equal(result.candidates.length, 0);
  assert.equal(result.constraintIssues.some((issue) => issue.code === "maximum-transfer-time-exceeded"), true);
});

test("bounded generation adds deterministic country-block candidates without exceeding twenty", () => {
  const stops = [
    countryStop("in-1", "IN", 0),
    countryStop("cn-1", "CN", 1),
    countryStop("jp-1", "JP", 2),
    countryStop("in-2", "IN", 3),
    countryStop("cn-2", "CN", 4),
    countryStop("jp-2", "JP", 5),
    countryStop("ae", "AE", 6),
  ];
  const first = generateRouteCandidates({ origin, stops, estimateLeg: estimatedLeg });
  const second = generateRouteCandidates({ origin, stops, estimateLeg: estimatedLeg });
  const countryBlocks = first.candidates.filter((candidate) => candidate.source === "country-block");

  assert.ok(countryBlocks.length > 0);
  assert.ok(countryBlocks.some((candidate) => analyzeRouteCountryContinuity(candidate.stops).reentryCount === 0));
  assert.ok(first.candidates.length <= 20);
  assert.deepEqual(
    first.candidates.map((candidate) => ({ source: candidate.source, ids: candidate.stops.map((item) => item.id) })),
    second.candidates.map((candidate) => ({ source: candidate.source, ids: candidate.stops.map((item) => item.id) })),
  );
});

test("country-block grouping improves known spans without crossing an unknown barrier", () => {
  const unknown = countryStop("unknown", undefined, 2);
  const stops = [
    countryStop("in-1", "IN", 0),
    countryStop("in-2", "IN", 1),
    unknown,
    countryStop("jp-1", "JP", 3),
    countryStop("cn-1", "CN", 4),
    countryStop("jp-2", "JP", 5),
    countryStop("ae-1", "AE", 6),
  ];
  const generated = generateRouteCandidates({ origin, stops, estimateLeg: estimatedLeg });
  const countryBlocks = generated.candidates.filter((candidate) => candidate.source === "country-block");

  assert.ok(countryBlocks.some(({ stops: candidateStops }) =>
    candidateStops.map((item) => item.id).join("|") === "in-1|in-2|unknown|jp-1|jp-2|cn-1|ae-1"));
  assert.ok(generated.candidates.every(({ stops: candidateStops }) => candidateStops.indexOf(unknown) === 2));
});

test("country-block candidates preserve fixed gateways, required and repeated occurrences", () => {
  const stops = [
    countryStop("in-gateway", "IN", 0, "mumbai"),
    countryStop("cn-1", "CN", 1),
    countryStop("in-return", "IN", 2, "mumbai"),
    countryStop("jp-1", "JP", 3),
    countryStop("cn-2", "CN", 4),
    countryStop("jp-2", "JP", 5),
    countryStop("ae-end", "AE", 6),
  ];
  const generated = generateRouteCandidates({
    origin,
    stops,
    constraints: { fixedStartStopId: "in-gateway", fixedEndStopId: "ae-end", requiredStopIds: ["in-return"] },
    estimateLeg: estimatedLeg,
  });

  assert.ok(generated.candidates.some((candidate) => candidate.source === "country-block"));
  for (const candidate of generated.candidates) {
    assert.equal(candidate.stops[0]?.id, "in-gateway");
    assert.equal(candidate.stops.at(-1)?.id, "ae-end");
    assert.equal(candidate.stops.filter((item) => item.canonicalPlaceId === "mumbai").length, 2);
    assert.ok(candidate.stops.some((item) => item.id === "in-return"));
  }
});

test("retains one concrete hard-transport rejection for a lower-block order", () => {
  const stops = [
    countryStop("in-1", "IN", 0),
    countryStop("ae-1", "AE", 1),
    countryStop("in-2", "IN", 2),
    countryStop("cn-1", "CN", 3),
    countryStop("cn-2", "CN", 4),
    countryStop("jp-1", "JP", 5),
    countryStop("jp-2", "JP", 6),
  ];
  const hardTransportLeg = (from: { name: string; coordinates?: [number, number] }, to: PlannerStop): EstimatedLeg => ({
    ...estimatedLeg(from, to),
    durationMinutes: from.name === "in-1" && to.id === "in-2" ? 300 : 30,
  });
  const generated = generateRouteCandidates({
    origin,
    stops,
    constraints: { maximumTransferMinutes: 120 },
    estimateLeg: hardTransportLeg,
  });
  const rejection = generated.countryBlockRejections.find((item) => item.countryCode === "IN");

  assert.deepEqual(rejection?.stopIds, ["in-1", "in-2", "ae-1", "cn-1", "cn-2", "jp-1", "jp-2"]);
  assert.deepEqual(rejection?.issueCodes, ["maximum-transfer-time-exceeded"]);
  assert.deepEqual(rejection?.constraintIds, ["maximum-transfer-minutes:120"]);
  assert.equal(generated.candidates.some((candidate) => candidate.stops.map((item) => item.id).join("|") === rejection?.stopIds.join("|")), false);
});
