import assert from "node:assert/strict";
import test from "node:test";
import { generateRouteCandidates } from "../lib/easyt/route-candidates.ts";
import type { EstimatedLeg, PlannerStop } from "../lib/easyt/planner.ts";

const stop = (id: string, longitude: number): PlannerStop => ({ id, name: id, country: "Testland", coordinates: [longitude, 0] });
const origin = { name: "Origin", coordinates: [-1, 0] as [number, number] };
const estimatedLeg = (from: { coordinates?: [number, number] }, to: PlannerStop): EstimatedLeg => {
  const distanceKm = Math.abs((to.coordinates?.[0] ?? 0) - (from.coordinates?.[0] ?? 0)) * 100;
  return { mode: "train", distanceKm, durationMinutes: distanceKm, label: "Test connection", note: "Planning estimate.", confidence: "medium" };
};

test("every candidate preserves fixed start and end", () => {
  const stops = [stop("bangkok", 0), stop("siem-reap", 1), stop("phnom-penh", 2), stop("hcmc", 3)];
  const result = generateRouteCandidates({ origin, stops, constraints: { fixedStartStopId: "bangkok", fixedEndStopId: "hcmc" }, estimateLeg: estimatedLeg });
  assert.ok(result.candidates.length > 0);
  assert.equal(result.candidates.every((candidate) => candidate.stops[0]?.id === "bangkok" && candidate.stops.at(-1)?.id === "hcmc"), true);
});

test("required destinations remain in every candidate", () => {
  const stops = [stop("a", 0), stop("anchor", 1), stop("b", 2)];
  const result = generateRouteCandidates({ origin, stops, constraints: { requiredStopIds: ["anchor"] }, estimateLeg: estimatedLeg });
  assert.equal(result.candidates.every((candidate) => candidate.stops.some((item) => item.id === "anchor")), true);
});

test("fixed endpoints only permute flexible middle stops", () => {
  const stops = [stop("bangkok", 0), stop("siem-reap", 1), stop("phnom-penh", 2), stop("hcmc", 3)];
  const result = generateRouteCandidates({ origin, stops, constraints: { fixedStartStopId: "bangkok", fixedEndStopId: "hcmc" }, estimateLeg: estimatedLeg });
  assert.deepEqual(result.candidates.map((candidate) => candidate.stops.map((item) => item.id)), [
    ["bangkok", "siem-reap", "phnom-penh", "hcmc"],
    ["bangkok", "phnom-penh", "siem-reap", "hcmc"],
  ]);
});

test("a genuinely identical fixed first and last active stop remains a hard conflict", () => {
  const stops = [stop("boundary", 0), stop("middle", 1)];
  const result = generateRouteCandidates({
    origin,
    stops,
    constraints: { fixedStartStopId: "boundary", fixedEndStopId: "boundary" },
    estimateLeg: estimatedLeg,
  });
  assert.equal(result.candidates.length, 0);
  assert.deepEqual(result.constraintIssues.find((issue) => issue.code === "fixed-endpoint-conflict")?.stopIds, ["boundary"]);
});

test("the original route remains a candidate when hard constraints allow it", () => {
  const stops = [stop("c", 2), stop("a", 0), stop("b", 1)];
  const result = generateRouteCandidates({ origin, stops, estimateLeg: estimatedLeg });
  const original = result.candidates.find((candidate) => candidate.metadata.matchesOriginalOrder);
  assert.deepEqual(original?.stops.map((item) => item.id), ["c", "a", "b"]);
  assert.equal(original?.source, "existing");
});

test("unlinked fixed commitments conservatively protect the entered order", () => {
  const stops = [stop("c", 2), stop("a", 0), stop("b", 1)];
  const result = generateRouteCandidates({ origin, stops, constraints: { fixedCommitments: [{ label: "Wedding", date: "2026-09-10" }] }, estimateLeg: estimatedLeg });
  assert.equal(result.candidates.length, 1);
  assert.deepEqual(result.candidates[0]?.stops.map((item) => item.id), ["c", "a", "b"]);
  assert.equal(result.candidates[0]?.source, "existing");
});

test("candidate orders generated by multiple paths are deduplicated by stop ID", () => {
  const stops = Array.from({ length: 7 }, (_, index) => stop(`stop-${index}`, index));
  const result = generateRouteCandidates({ origin, stops, estimateLeg: estimatedLeg });
  const keys = result.candidates.map((candidate) => candidate.stops.map((item) => item.id).join("|"));
  assert.equal(new Set(keys).size, keys.length);
  assert.ok(result.rawCandidateCount >= result.candidates.length);
});

test("seven and fifteen stop routes use bounded candidate generation", () => {
  for (const count of [7, 15]) {
    const result = generateRouteCandidates({ origin, stops: Array.from({ length: count }, (_, index) => stop(`stop-${index}`, index)), estimateLeg: estimatedLeg });
    assert.equal(result.strategy, "bounded");
    assert.ok(result.candidates.length >= 5);
    assert.ok(result.candidates.length <= 20);
    assert.equal(result.truncated, true);
  }
});

test("hard transport conflicts prune while soft preferences do not", () => {
  const stops = [stop("a", 0), stop("b", 1)];
  const roadLeg = (from: { coordinates?: [number, number] }, to: PlannerStop): EstimatedLeg => ({ ...estimatedLeg(from, to), mode: "road", confidence: "high" });
  const hard = generateRouteCandidates({ origin, stops, constraints: { avoidDriving: true }, estimateLeg: roadLeg });
  assert.equal(hard.candidates.length, 0);
  assert.equal(hard.constraintIssues.some((issue) => issue.code === "forbidden-transport-mode"), true);

  const soft = generateRouteCandidates({ origin, stops, constraints: { transportModes: ["train"] }, estimateLeg: roadLeg });
  assert.ok(soft.candidates.length > 0);

  const heuristicRoadLeg = (from: { coordinates?: [number, number] }, to: PlannerStop): EstimatedLeg => ({ ...roadLeg(from, to), confidence: "medium" });
  const heuristicHard = generateRouteCandidates({ origin, stops, constraints: { avoidDriving: true }, estimateLeg: heuristicRoadLeg });
  assert.equal(heuristicHard.candidates.length, 0);
  assert.equal(heuristicHard.constraintIssues.some((issue) => issue.code === "forbidden-transport-mode"), true);
});

test("a required-stop maximum contradiction returns a structured issue without dropping an anchor", () => {
  const stops = [stop("a", 0), stop("b", 1), stop("c", 2)];
  const result = generateRouteCandidates({
    origin,
    stops,
    constraints: { requiredStopIds: ["a", "b", "c"], maximumStops: 2 },
    estimateLeg: estimatedLeg,
  });
  assert.equal(result.candidates.length, 0);
  assert.equal(result.constraintIssues.some((issue) => issue.code === "required-stops-exceed-maximum"), true);
  assert.equal(result.constraintIssues.some((issue) => issue.code === "maximum-stops-exceeded"), true);
});

test("a maximum transfer ceiling rejects every violating candidate before scoring", () => {
  const stops = [stop("a", 0), stop("b", 1), stop("c", 2)];
  const threeHours = (from: { coordinates?: [number, number] }, to: PlannerStop): EstimatedLeg => ({
    ...estimatedLeg(from, to),
    durationMinutes: 180,
  });
  const result = generateRouteCandidates({
    origin,
    stops,
    constraints: { maximumTransferMinutes: 120 },
    estimateLeg: threeHours,
  });

  assert.equal(result.candidates.length, 0);
  assert.equal(result.constraintIssues.some((issue) => issue.code === "maximum-transfer-time-exceeded"), true);
});
