import assert from 'node:assert/strict';
import test from 'node:test';
import {canonicalRouteFixture} from './fixtures/batch14-route-documents.ts';
import {requireReadableTripDocument,prepareTripDocumentForWrite} from '../lib/easyt/trip-document.ts';
import {builderStructuralSnapshot,type BuilderAcceptedEdit} from '../lib/easyt/trip-builder-edit.ts';
import {prepareBuilderHandlerEdit} from '../lib/easyt/trip-builder-handler-contract.ts';
import {builderDocumentFingerprint} from '../lib/easyt/trip-builder-document-commit.ts';
import {pendingBuilderReconciliationUnits,reconcileBuilderDependencies} from '../lib/easyt/trip-builder-reconciliation.ts';
import {authoredContentKey,retainRemovedAuthoredContent,removeRetainedAuthoredContent,moveRetainedAuthoredContent,restoreRetainedAuthoredContent} from '../lib/easyt/trip-retained-authored-content.ts';
import type {CanonicalEasyTTrip} from '../lib/easyt/trip.ts';
const fixture=()=>requireReadableTripDocument(canonicalRouteFixture());
function apply(trip:CanonicalEasyTTrip,edit:BuilderAcceptedEdit){const r=prepareBuilderHandlerEdit(trip,edit,builderDocumentFingerprint(trip));assert.ok(r.ok,JSON.stringify(r));return r.trip;}
function nights(trip:CanonicalEasyTTrip,id:string,count:number){return apply(trip,{kind:'nights',stopId:id,intentId:trip.brief.intent.route.destinations.find(i=>i.stopIds.includes(id))!.id,nights:count});}
function authored(){const t=fixture(),d=t.planItems.find(d=>d.stopId==='kyoto'&&d.dayNumber===7)!;Object.assign(d,{notes:['Ticket reminder','Private activity'],noteDayParts:['morning','evening'],startsAt:'09:00',endsAt:'11:00',bookingUrl:'https://example.invalid/booking',sourceUrl:'https://example.invalid/source',image:'https://example.invalid/image',latitude:35,longitude:135});t.brief.dayNotes={[7]:['Bring tickets']};t.brief.customActivities={[7]:['Private activity']};t.brief.mapPins=[{id:'pin:retired',title:'Meet here',dayNumber:7,category:'activity',longitude:135,latitude:35}];t.brief.itineraryIdeas=[{id:'day:idea',stopId:'kyoto',dayId:d.id,placeId:'saved',title:'Provider reference',description:'Full provenance',category:'activity',source:'personalised-recommendation',reasons:[],providerProductId:'p:123',sourceUrl:'https://example.invalid/provider'},{id:'stop:idea',stopId:'kyoto',placeId:'later',title:'Stop scoped idea',description:'Keep me live',category:'activity',source:'personalised-recommendation',reasons:[]}];return {t,d:structuredClone(d)};}
test('shrinking a surviving stop retains exact full source day without nearest-day reassignment',()=>{const {t,d}=authored(),next=nights(t,'kyoto',2);assert.equal(next.planItems.filter(d=>d.stopId==='kyoto').length,2);const e=next.brief.retainedAuthoredContent!.entries.find(e=>e.days.some(x=>x.sourceDay.id===d.id))!;assert.equal(e.sourceKind,'retired_day');assert.deepEqual(e.sourceStop,t.stops[1]);assert.deepEqual(e.days,[{sourceDay:d,dayNotes:['Bring tickets'],customActivities:['Private activity']}]);assert.deepEqual(e.itineraryIdeas,[t.brief.itineraryIdeas![0]]);assert.deepEqual(e.mapPins,t.brief.mapPins);assert.deepEqual(next.brief.itineraryIdeas,[t.brief.itineraryIdeas![1]]);assert.deepEqual(next.brief.mapPins,[]);assert.equal(Object.values(next.brief.dayNotes??{}).flat().includes('Bring tickets'),false);assert.equal(next.planItems.some(x=>x.notes.includes('Private activity')),false);assert.deepEqual(next.planItems.filter(d=>d.stopId==='tokyo'),t.planItems.filter(d=>d.stopId==='tokyo'));assert.deepEqual(requireReadableTripDocument(JSON.parse(JSON.stringify(prepareTripDocumentForWrite(next)))).brief.retainedAuthoredContent,next.brief.retainedAuthoredContent);});
test('grow/shrink/retry never resurrects old day IDs or consumes same-stop retained history',()=>{const {t,d}=authored();let next=nights(t,'kyoto',2);const old=structuredClone(next.brief.retainedAuthoredContent);next=nights(next,'kyoto',3);const added=next.planItems.filter(x=>x.stopId==='kyoto')[2]!;assert.notEqual(added.id,d.id);assert.deepEqual(next.brief.retainedAuthoredContent,old);assert.equal(added.notes.includes('Private activity'),false);const first=structuredClone(next.planItems);next=reconcileBuilderDependencies(next,pendingBuilderReconciliationUnits(next)).trip;assert.deepEqual(next.planItems,first);next=nights(next,'kyoto',2);assert.equal(next.brief.retainedAuthoredContent!.entries.length,2);next=nights(next,'kyoto',3);assert.notEqual(next.planItems.filter(x=>x.stopId==='kyoto')[2]!.id,added.id);assert.deepEqual(next.brief.retainedAuthoredContent!.entries[0],old!.entries[0]);assert.deepEqual(restoreRetainedAuthoredContent(next,[old!.entries[0].sourceStop]),next,'restoring a stop cannot consume or restore retired-day history');});
test('zero-night non-final and zero-night final stops use the existing calendar convention',()=>{let t=fixture();t=nights(t,'tokyo',0);assert.equal(t.planItems.filter(d=>d.stopId==='tokyo').length,0);t=nights(t,'hiroshima',0);assert.equal(t.planItems.filter(d=>d.stopId==='hiroshima').length,1);assert.deepEqual(t.brief.intent.route.orderedStopIds,['tokyo','kyoto','hiroshima']);assert.equal(t.endDate,'2026-10-19','underallocation is never repaired by altering fixed dates');});
test('timed day that cannot follow a shifted arrival is retained rather than moved',()=>{const {t}=authored();const source=t.planItems.find(d=>d.dayNumber===7)!;const next=nights(t,'tokyo',5);assert.equal(next.planItems.some(d=>d.id===source.id),false);assert.deepEqual(next.brief.retainedAuthoredContent!.entries.find(e=>e.days.some(d=>d.sourceDay.id===source.id))!.days[0].sourceDay,source);assert.ok(next.brief.cascadeStatus!.conflicts.length);assert.equal(next.brief.itineraryIdeas!.some(i=>i.id==='day:idea'),false);});
test('exact structural inverse restores original calendar and only corresponding snapshots',()=>{const {t}=authored();const s=builderStructuralSnapshot(t);let next=nights(t,'kyoto',2);assert.equal(next.planItems.some(d=>d.id==='japan-day-7'),false);const unchanged=next.planItems.find(d=>d.stopId==='tokyo')!;unchanged.notes.push('Later unrelated authored edit');unchanged.contextNotes=['Later generated response'];next=apply(next,{kind:'structural-inverse',snapshot:s});assert.deepEqual(next.planItems.map(d=>[d.id,d.dayNumber,d.date]),t.planItems.map(d=>[d.id,d.dayNumber,d.date]));assert.deepEqual(next.planItems.find(d=>d.stopId==='kyoto'&&d.dayNumber===7),t.planItems.find(d=>d.dayNumber===7));assert.ok(next.planItems.find(d=>d.stopId==='tokyo')!.notes.includes('Later unrelated authored edit'));assert.deepEqual(next.planItems.find(d=>d.stopId==='tokyo')!.contextNotes,['Later generated response']);assert.deepEqual(next.brief.dayNotes,t.brief.dayNotes);assert.deepEqual(next.brief.customActivities,t.brief.customActivities);assert.deepEqual(next.brief.mapPins,t.brief.mapPins);assert.deepEqual(next.brief.itineraryIdeas,t.brief.itineraryIdeas);assert.equal(Boolean(next.brief.retainedAuthoredContent?.entries.some(e=>e.days.some(d=>d.sourceDay.id==='japan-day-7'))),false);});
test('stale full retained selection and incompatible booked moves cannot consume snapshots',()=>{const {t}=authored();const next=nights(t,'kyoto',2),entry=next.brief.retainedAuthoredContent!.entries[0],selection={entryId:entry.id,expectedContentKey:authoredContentKey(entry),dayIds:[entry.days[0].sourceDay.id]};const stale={...selection,expectedContentKey:'stale'};assert.equal(removeRetainedAuthoredContent(next,stale).ok,false);assert.equal(moveRetainedAuthoredContent(next,selection,{stopId:'tokyo',dayId:next.planItems[0].id}).ok,false);const removed=removeRetainedAuthoredContent(next,selection);assert.ok(removed.ok);assert.deepEqual(removed.trip.brief.retainedAuthoredContent!.entries[0].itineraryIdeas,entry.itineraryIdeas);assert.deepEqual(removed.trip.brief.retainedAuthoredContent!.entries[0].mapPins,entry.mapPins);});

test('Undo rejects an explicitly consumed source and an authored new slot',()=>{const {t}=authored();const s=builderStructuralSnapshot(t);let next=nights(t,'kyoto',2);const e=next.brief.retainedAuthoredContent!.entries[0];const removed=removeRetainedAuthoredContent(next,{entryId:e.id,expectedContentKey:authoredContentKey(e),dayIds:[e.days[0].sourceDay.id]});assert.ok(removed.ok);assert.equal(prepareBuilderHandlerEdit(removed.trip as CanonicalEasyTTrip,{kind:'structural-inverse',snapshot:s},builderDocumentFingerprint(removed.trip)).ok,false);const original=fixture(),frame=builderStructuralSnapshot(original);next=nights(original,'tokyo',5);next.planItems.find(d=>d.id.startsWith(original.id+'-calendar:'))!.notes=['Later authored choice'];assert.equal(prepareBuilderHandlerEdit(next,{kind:'structural-inverse',snapshot:frame},builderDocumentFingerprint(next)).ok,false);});

test('same source day with different semantic snapshots retains distinct immutable generations',()=>{const {t,d}=authored();const next=nights(t,'kyoto',2);const earlier=structuredClone(next.brief.retainedAuthoredContent!.entries[0]);const changed=structuredClone(t);changed.planItems.find(day=>day.id===d.id)!.notes.push('A different immutable source');const retained=retainRemovedAuthoredContent(changed,next);assert.equal(retained.brief.retainedAuthoredContent!.entries.length,2);assert.deepEqual(retained.brief.retainedAuthoredContent!.entries[0],earlier);assert.notEqual(retained.brief.retainedAuthoredContent!.entries[0].id,retained.brief.retainedAuthoredContent!.entries[1].id);const dedup=retainRemovedAuthoredContent(changed,retained);assert.deepEqual(dedup.brief.retainedAuthoredContent,retained.brief.retainedAuthoredContent);});

test('balanced calendar remains in conflict until incompatible retired booking is reviewed',()=>{const {t}=authored();let next=nights(t,'tokyo',5);next=nights(next,'kyoto',2);assert.equal(next.stops.reduce((sum,s)=>sum+(s.nights??0),0),9);const worker=reconcileBuilderDependencies(next,pendingBuilderReconciliationUnits(next));assert.ok(worker.trip.brief.cascadeStatus!.routeReconciliation!.residual.some(unit=>unit.phase==='conflict'));assert.ok(worker.trip.brief.cascadeStatus!.conflicts.some(value=>value.includes('retained day')));});

test('repeated occurrence names and area totals retain independent day and night ownership',()=>{let t=fixture();t.stops[1].name=t.stops[0].name;t.brief.intent.route.destinations[1].selectedPlace!.name=t.stops[0].name;const a=t.brief.intent.route.destinations[0],b=t.brief.intent.route.destinations[1];t.brief.intent.route.destinations=[{...a,id:'area:japan',kind:'planning_area',sourceText:'Japan',requestedNights:7,stopIds:[a.stopIds[0],b.stopIds[0]]},t.brief.intent.route.destinations[2]];t=nights(t,'tokyo',5);t=nights(t,'kyoto',2);assert.equal(t.brief.intent.route.destinations[0].requestedNights,7);assert.deepEqual(t.planItems.filter(d=>d.stopId==='tokyo').map(d=>d.dayNumber),[1,2,3,4,5]);assert.deepEqual(t.planItems.filter(d=>d.stopId==='kyoto').map(d=>d.dayNumber),[6,7]);assert.equal(new Set(t.planItems.map(d=>d.id)).size,10);});
test('held unresolved nights and fixed date expansion/contraction are preserved rather than clipped',()=>{let t=fixture();t.brief.intent.route.destinations.push({id:'held:mostar',selectedPlace:null,sourceText:'Mostar',kind:'overnight_place',resolution:'unavailable',requestedNights:2,routeMembership:'required',stopIds:[]});const held=structuredClone(t.brief.intent.route.destinations.at(-1));t=apply(t,{kind:'dates',startDate:'2026-10-12',endDate:'2026-10-17'});assert.equal(t.planItems.length,10);assert.deepEqual(t.brief.intent.route.destinations.at(-1),held);assert.ok(t.brief.cascadeStatus!.conflicts.length);const ids=t.planItems.map(d=>d.id);t=apply(t,{kind:'dates',startDate:'2026-10-12',endDate:'2026-10-24'});assert.deepEqual(t.planItems.map(d=>d.id),ids);assert.equal(t.planItems.length,10);assert.equal(t.endDate,'2026-10-24');assert.deepEqual(t.brief.intent.route.destinations.at(-1),held);});

test('a timed day-owned reference is retained when its container would change date',()=>{const t=fixture(),day=t.planItems.find(d=>d.stopId==='kyoto')!;t.brief.itineraryIdeas=[{id:'timed-reference',stopId:'kyoto',dayId:day.id,placeId:'p',title:'Timed visit',description:'Do not move this time',category:'activity',source:'traveller-visit-intent',reasons:[],startsAt:'09:00'}];const next=nights(t,'tokyo',5);assert.equal(next.planItems.some(d=>d.id===day.id),false);assert.deepEqual(next.brief.retainedAuthoredContent!.entries.find(e=>e.days.some(d=>d.sourceDay.id===day.id))!.itineraryIdeas,t.brief.itineraryIdeas);});
test('Undo cannot move a later booked survivor back onto its old date',()=>{const t=fixture(),snapshot=builderStructuralSnapshot(t),next=nights(t,'tokyo',5);const survivor=next.planItems.find(d=>d.stopId==='kyoto')!;survivor.bookingUrl='https://example.invalid/later-booking';survivor.startsAt='09:00';assert.equal(prepareBuilderHandlerEdit(next,{kind:'structural-inverse',snapshot},builderDocumentFingerprint(next)).ok,false);});

test('deliberate consumption cannot allow a genuinely new slot to reuse a retired live ID',()=>{let t=nights(fixture(),'tokyo',5);const id=t.planItems.find(d=>d.id.includes('-calendar:'))!.id;t=nights(t,'tokyo',4);const e=t.brief.retainedAuthoredContent!.entries.find(e=>e.days.some(d=>d.sourceDay.id===id))!;t=apply(t,{kind:'retained-content-remove',selection:{entryId:e.id,expectedContentKey:authoredContentKey(e),dayIds:[id]}});assert.equal(t.brief.retainedAuthoredContent,undefined);t=nights(t,'tokyo',5);assert.notEqual(t.planItems.find(d=>d.id.includes('-calendar:'))!.id,id);});
