export type VisualAuditClassification =
  | "CANONICAL"
  | "DUPLICATE / MIGRATION CANDIDATE"
  | "INTENTIONAL EXCEPTION"
  | "UNDECIDED";

export type VisualAuditRecord = {
  family: string;
  semanticJob: string;
  implementation: string;
  owner: string;
  consumers: string[];
  differences: string;
  storybookCoverage: string;
  classification: VisualAuditClassification;
  migrationStatus: string;
  canonicalReference?: string;
};

export type CanonicalUiOwner = {
  family: string;
  semanticJob: string;
  owner: string;
  storybookCoverage: string;
  meaningfulStates: string[];
  boundary: string;
};

export const canonicalUiOwners: CanonicalUiOwner[] = [
  {
    family: "Button",
    semanticJob: "Primary, secondary, quiet, destructive and link actions",
    owner: "EasyTButton / EasyTLinkButton · components/easyt/easyt-controls.tsx",
    storybookCoverage: "02 Controls / Buttons, fields and segments",
    meaningfulStates: ["default", "focus", "disabled", "loading", "icon-only", "narrow"],
    boundary: "Composite canvas controls may remain product-owned only when their keyboard or spatial contract differs.",
  },
  {
    family: "Field",
    semanticJob: "Labelled input, select and textarea with help or validation",
    owner: "EasyTField / EasyTSelect / EasyTTextArea · components/easyt/easyt-controls.tsx",
    storybookCoverage: "02 Controls / Buttons, fields and segments; Date, quantity and forms",
    meaningfulStates: ["empty", "populated", "focus", "disabled", "error", "hint", "long content", "narrow"],
    boundary: "Date, quantity, voice and map-search composites use their dedicated owners instead of imitating a plain field.",
  },
  {
    family: "Segmented selection",
    semanticJob: "Choose one compact view or filter while keeping the available set visible",
    owner: "EasyTSegmentedControl · components/easyt/easyt-controls.tsx",
    storybookCoverage: "02 Controls / Buttons, fields and segments / Segmented",
    meaningfulStates: ["selected", "unselected", "counts", "controlled region", "mobile"],
    boundary: "Use link navigation for destinations and dedicated radio/checkbox anatomy for form answers; a segment changes the current view in place.",
  },
  {
    family: "Card",
    semanticJob: "Group product information and its contextual actions",
    owner: "The closest product-pattern component; Morrovia intentionally has no universal Card",
    storybookCoverage: "05 Product Patterns; 06 Audit / Card comparison",
    meaningfulStates: ["content-specific empty/error states", "long content", "missing imagery", "responsive"],
    boundary: "Share foundations and controls, not route/trip/stay/task/passport/map anatomy.",
  },
  {
    family: "Status",
    semanticJob: "Persistent save, recovery, confirmation and generic feedback truth",
    owner: "Morrovia feedback family · components/easyt/morrovia-feedback.tsx",
    storybookCoverage: "03 Status & Feedback / Confirmation and recovery; Status catalogue",
    meaningfulStates: ["info", "success", "warning", "error", "saving", "device-safe", "focus-managed confirmation", "mobile"],
    boundary: "Domain health, booking and readiness state remains with the product component that owns that state machine.",
  },
  {
    family: "Contextual disclosure",
    semanticJob: "Explain AI, privacy, provider or product context without displacing the primary task",
    owner: "MorroviaContextualDisclosure · components/easyt/morrovia-feedback.tsx",
    storybookCoverage: "03 Status & Feedback / Confirmation and recovery / Contextual transparency disclosure",
    meaningfulStates: ["collapsed", "expanded", "keyboard close", "outside close", "focus return", "start/end alignment", "mobile"],
    boundary: "Use a legal page or persistent notice when the information must remain continuously visible; this owner is for contextual non-modal disclosure.",
  },
  {
    family: "Privacy choice",
    semanticJob: "Collect and revise analytics and affiliate-tracking consent",
    owner: "PrivacyConsent / CookiePreferences · components/privacy-consent.tsx and components/cookie-preferences.tsx",
    storybookCoverage: "03 Status & Feedback / Privacy choices",
    meaningfulStates: ["first visit", "saved preferences", "checkbox selection", "mobile"],
    boundary: "Consent state and storage semantics stay with lib/privacy-consent.ts; generic fields must not reproduce this legal workflow.",
  },
  {
    family: "Progress",
    semanticJob: "Local waiting, staged planning, retry and completion progress",
    owner: "Morrovia loading family · components/easyt/morrovia-loading-states.tsx",
    storybookCoverage: "03 Status & Feedback / Loading and progress",
    meaningfulStates: ["loading", "long wait", "error", "retry", "success", "reduced motion", "mobile/tablet"],
    boundary: "Keep the affected context visible; map loading retains its spatial owner and layout.",
  },
  {
    family: "Trip capture",
    semanticJob: "Capture a natural-language trip idea with dates, travellers, interests and optional voice",
    owner: "MorroviaTripCapture · components/easyt/morrovia-trip-capture.tsx",
    storybookCoverage: "05 Product Patterns / Trip capture",
    meaningfulStates: ["first visit", "filled", "AI/speech transparency", "loading", "error", "mobile/tablet"],
    boundary: "Homepage and Builder own their surrounding workflow and analytics; the shared capture owner keeps the input, voice and supporting controls aligned.",
  },
  {
    family: "Trip navigation",
    semanticJob: "Switch among Overview, Map and Itinerary within one trip",
    owner: "TripShellNavigation · components/easyt/trip-shell-client.tsx",
    storybookCoverage: "04 Structure / Trip shell; Dialogs, overlays and navigation",
    meaningfulStates: ["overview selected", "map selected", "itinerary selected", "mobile", "tablet", "desktop"],
    boundary: "This is trip-local link navigation, not a segmented control or a second global navigation.",
  },
  {
    family: "Route row",
    semanticJob: "Present a route result or a sequenced public-route stop",
    owner: "DiscoveryBrowser and RouteDetailView · app/journey/discover and app/journey/routes/[slug]",
    storybookCoverage: "05 Product Patterns / Routes and Routes / Route detail",
    meaningfulStates: ["standard", "long route", "missing imagery", "unknown transfer", "allocation warning", "mobile/tablet/desktop"],
    boundary: "Discovery results and sequenced stop rows share route truth but keep different interaction and information contracts.",
  },
  {
    family: "Itinerary row",
    semanticJob: "Select, inspect and directly edit an item in a trip day",
    owner: "TimelineRow / TransferRow within TripItineraryWorkspace · components/easyt/trip-itinerary-workspace.tsx",
    storybookCoverage: "05 Product Patterns / Trip workspace / Itinerary",
    meaningfulStates: ["selected", "editable", "locked/booked", "pending", "partial data", "without time", "long content", "responsive"],
    boundary: "Rows remain workspace-owned because they are coupled to canonical itinerary mutation, booking protection and day selection.",
  },
  {
    family: "Recommendation",
    semanticJob: "Explain a trip recommendation or offer a contextual place to add",
    owner: "Trip recommendations in TripOverviewWorkspace/TripItineraryWorkspace; place discovery via JourneyItineraryRefinement and JourneyLocalFinder",
    storybookCoverage: "05 Product Patterns / Trip workspace / Overview and Itinerary; Builder and planner",
    meaningfulStates: ["open advice", "contextual suggestion", "already planned suppression", "provider unavailable", "add pending", "mobile"],
    boundary: "Recommendation presentation may differ, but successful Add must use the trip workspace's canonical mutation path.",
  },
  {
    family: "Booking/readiness action",
    semanticJob: "Show the next truthful preparation or provider action without implying a booking",
    owner: "TripPreparationTaskSection with lib/easyt/trip-prep.ts and lib/easyt/trip-overview-readiness.ts",
    storybookCoverage: "05 Product Patterns / Trip workspace / Overview; Catalogue / Preparation and readiness task; 03 Status & Feedback / Affiliate boundary",
    meaningfulStates: ["urgent", "in progress", "complete", "provider unavailable", "external provider opened", "responsive"],
    boundary: "Opening an affiliate/provider site is not booked state; confirmation stays derived from stored trip data.",
  },
  {
    family: "Trip health",
    semanticJob: "Explain whether the current route and itinerary need attention",
    owner: "JourneyTripQuality with lib/easyt/review.ts · components/journey-trip-quality.tsx",
    storybookCoverage: "03 Status & Feedback / Status catalogue; 05 Product Patterns / Trip workspace / Overview",
    meaningfulStates: ["healthy", "needs attention", "unknown", "actionable issue", "responsive"],
    boundary: "Trip Health is domain truth, not a generic status-banner tone; its findings remain derived from review logic.",
  },
  {
    family: "Map overlay",
    semanticJob: "Present loading, selection and contextual actions without losing spatial context",
    owner: "TripMapWorkspace / JourneyPlannerMap with MorroviaMapLoading",
    storybookCoverage: "05 Product Patterns / Trip workspace / Map; 03 Status & Feedback / Loading and progress",
    meaningfulStates: ["route", "selected stop", "selected place", "loading", "provider unavailable", "mobile/tablet/desktop"],
    boundary: "Provider-map geometry and canvas controls stay spatially owned; generic panels must not be layered over the map by visual resemblance alone.",
  },
  {
    family: "AI / Copilot",
    semanticJob: "Answer contextual questions and present proposed trip changes for explicit review and apply",
    owner: "EasyTTripCopilot · components/easyt/easyt-trip-copilot.tsx",
    storybookCoverage: "05 Product Patterns / Luna AI assistant",
    meaningfulStates: ["answer", "proposed change", "provider failure", "explicit apply", "mobile"],
    boundary: "Luna may recommend and preview, but canonical mutation and persistence owners apply consequential changes.",
  },
];

export const visualAuditRecords: VisualAuditRecord[] = [
  {
    family: "Typography",
    semanticJob: "Display, product copy and metadata roles",
    implementation: "Morrovia display, UI and metadata token families",
    owner: "app/journey/journey-design.css",
    consumers: ["All Journey surfaces", "Shared components", "Storybook"],
    differences: "Three families are canonical; readable body, supporting, control, metadata, eyebrow and fine-print declarations are named while display/heading scale remains page-owned.",
    storybookCoverage: "01 Foundations / Typography",
    classification: "CANONICAL",
    migrationStatus: "Stable source of truth; raw font-family and page-local framework-role audit debt are both zero. Semantic prose roles now prevent meaningful explanations from collapsing into metadata styling without creating a general-purpose type-size scale.",
  },
  {
    family: "Typography",
    semanticJob: "Page and section heading sizing",
    implementation: "Homepage, Builder, TripShell, Overview, Itinerary, Routes and account selectors",
    owner: "Page-owned CSS modules",
    consumers: ["Homepage", "Builder", "Overview", "Itinerary", "Routes", "Profile/auth"],
    differences: "Font sizes, weights, tracking and responsive clamps are locally owned and visibly close but not identical.",
    storybookCoverage: "06 Audit / Typography comparison",
    classification: "INTENTIONAL EXCEPTION",
    migrationStatus: "Keep page-owned within the documented archetypes; align family roles without inventing a global size scale.",
    canonicalReference: "Typography — --morrovia-display, --morrovia-ui and --morrovia-meta roles",
  },
  {
    family: "Colour",
    semanticJob: "Brand, action, signal, surface and semantic feedback colour",
    implementation: "--morrovia-* semantic colour tokens",
    owner: "app/journey/journey-design.css",
    consumers: ["All current Morrovia surfaces"],
    differences: "Indigo owns primary action, pink owns signal, and success/warning/danger retain semantic meaning.",
    storybookCoverage: "01 Foundations / Colours",
    classification: "CANONICAL",
    migrationStatus: "Stable source of truth.",
  },
  {
    family: "Colour",
    semanticJob: "Equivalent brand and neutral values",
    implementation: "Raw hex, rgb and rgba values grouped by the convergence audit",
    owner: "Page and component CSS",
    consumers: ["Homepage", "Builder", "Account", "Journey workspaces", "Stamps"],
    differences: "Near-identical purples, pinks, whites and greys are copied instead of named semantically.",
    storybookCoverage: "01 Foundations / Colours and 06 Audit / Colour comparison",
    classification: "DUPLICATE / MIGRATION CANDIDATE",
    migrationStatus: "Shared controls now use the canonical focus, action-hover and danger tokens; remaining values still require narrow semantic review.",
  },
  {
    family: "Spacing",
    semanticJob: "Component and page rhythm",
    implementation: "Observed repeated gaps, padding and margins",
    owner: "Component and page CSS",
    consumers: ["All surfaces"],
    differences: "No repository-wide named spacing scale exists today.",
    storybookCoverage: "01 Foundations / Spacing",
    classification: "DUPLICATE / MIGRATION CANDIDATE",
    migrationStatus: "Measured migration debt; reuse the closest production owner until a recurring semantic scale is proven.",
  },
  {
    family: "Borders & radii",
    semanticJob: "Controls, compact interactions and larger panels",
    implementation: "--morrovia-line, --morrovia-control-radius and --morrovia-radius",
    owner: "app/journey/journey-design.css",
    consumers: ["Shared controls", "Trip shell", "Feedback", "Current workspaces"],
    differences: "The two named radius roles are intentionally broad rather than a full scale.",
    storybookCoverage: "01 Foundations / Borders & radii",
    classification: "CANONICAL",
    migrationStatus: "Stable source of truth.",
  },
  {
    family: "Borders & radii",
    semanticJob: "Local control and card curvature",
    implementation: "Repeated numeric border-radius declarations",
    owner: "Page and component CSS",
    consumers: ["Builder", "Account", "Homepage", "Map", "Dashboard"],
    differences: "Several close values represent either token drift or product-specific anatomy.",
    storybookCoverage: "01 Foundations / Borders & radii and 06 Audit / Card comparison",
    classification: "DUPLICATE / MIGRATION CANDIDATE",
    migrationStatus: "Review by semantic job before replacing.",
  },
  {
    family: "Shadows",
    semanticJob: "Keyboard focus plus overlay and modal elevation",
    implementation: "--morrovia-focus-shadow, --morrovia-shadow-overlay and --morrovia-overlay",
    owner: "app/journey/journey-design.css",
    consumers: ["Interactive controls", "Dialogs", "Popovers", "Map overlays"],
    differences: "The 3px focus treatment and overlay elevation are separate semantic roles; neither is a general card shadow.",
    storybookCoverage: "01 Foundations / Shadows",
    classification: "CANONICAL",
    migrationStatus: "Canonical focus consumers use the complete focus-shadow role; overlay hierarchy remains unchanged.",
  },
  {
    family: "Shadows",
    semanticJob: "Card and panel elevation",
    implementation: "Repeated raw box-shadow declarations",
    owner: "Page and component CSS",
    consumers: ["Account", "Journey", "Homepage", "Builder", "Map"],
    differences: "Many subtle elevations are visually close but do not share a documented semantic contract.",
    storybookCoverage: "01 Foundations / Shadows and 06 Audit / Card comparison",
    classification: "DUPLICATE / MIGRATION CANDIDATE",
    migrationStatus: "Keep distinct until each elevation job is reviewed.",
  },
  {
    family: "Icons",
    semanticJob: "Interface and semantic iconography",
    implementation: "lucide-react",
    owner: "Component imports and EasyTButton icon contract",
    consumers: ["All Journey surfaces"],
    differences: "Shared actions use the canonical 16px treatment; composed products size icons locally.",
    storybookCoverage: "01 Foundations / Icons",
    classification: "CANONICAL",
    migrationStatus: "Do not introduce a competing icon library.",
  },
  {
    family: "Icons",
    semanticJob: "Spatial markers and image-led product marks",
    implementation: "Map markers, trip-image fallbacks and Stamps map marks",
    owner: "Map, TripShell and Stamps production components",
    consumers: ["Map", "Trip shell", "Stamps"],
    differences: "Canvas and identity marks need dimensions that differ from ordinary action icons.",
    storybookCoverage: "05 Product Patterns / Trip workspace and Stamps",
    classification: "INTENTIONAL EXCEPTION",
    migrationStatus: "Documented product-specific anatomy.",
    canonicalReference: "Icons — lucide-react and the EasyTButton action-icon contract",
  },
  {
    family: "Layout",
    semanticJob: "Editorial page width and gutters",
    implementation: "--morrovia-page",
    owner: "app/journey/journey-design.css",
    consumers: ["Homepage", "Routes", "Passport", "Public/legal"],
    differences: "1180px maximum with responsive gutters below 700px.",
    storybookCoverage: "01 Foundations / Layout & widths",
    classification: "CANONICAL",
    migrationStatus: "Stable for editorial surfaces.",
  },
  {
    family: "Layout",
    semanticJob: "Wide workflow, spatial and exploration canvases",
    implementation: "Builder, Map, TripShell workspace and Stamps widths",
    owner: "Their production CSS modules",
    consumers: ["Builder", "Map", "Trip workspaces", "Stamps"],
    differences: "These jobs deliberately exceed or bypass the editorial width.",
    storybookCoverage: "01 Foundations / Layout & widths and responsive workspace stories",
    classification: "INTENTIONAL EXCEPTION",
    migrationStatus: "Do not narrow to the editorial width.",
    canonicalReference: "Layout — --morrovia-page editorial width and gutters",
  },
  {
    family: "Buttons",
    semanticJob: "Primary, secondary, quiet, danger and button-like links",
    implementation: "EasyTButton and EasyTLinkButton",
    owner: "components/easyt/easyt-controls.tsx",
    consumers: ["Overview", "Trip shell", "Feedback", "Discover", "Passport", "Dashboard", "Shared forms"],
    differences: "Shared height, type, icon, disabled, loading and focus contracts.",
    storybookCoverage: "02 Controls / Buttons, fields and segments",
    classification: "CANONICAL",
    migrationStatus: "Default for new recurring Journey actions.",
  },
  {
    family: "Buttons",
    semanticJob: "Equivalent page-local actions",
    implementation: "Native and composite buttons styled in Builder, Map, planning, Stamps, Profile and Discover",
    owner: "Page and composed-workspace implementations",
    consumers: ["Builder", "Map", "Plan workspace", "Stamps", "Profile preference controls", "Discover image-led controls", "Dashboard composites"],
    differences: "Height, radius, weight, hover, focus and icon sizing vary by local selector.",
    storybookCoverage: "06 Audit / Button comparison",
    classification: "DUPLICATE / MIGRATION CANDIDATE",
    migrationStatus: "Dashboard status segments and gift-dialog actions plus Passport submit are migrated; remaining composite controls need keyboard proof.",
  },
  {
    family: "Form controls",
    semanticJob: "Labelled text, textarea, select and validation",
    implementation: "EasyTField, EasyTTextArea and EasyTSelect",
    owner: "components/easyt/easyt-controls.tsx",
    consumers: ["Profile", "Overview traveller details", "Passport selectors", "Discover labelled filters", "Dashboard gift dialog", "Shared forms"],
    differences: "Programmatic labels, hints, errors, disabled and focus states are built in.",
    storybookCoverage: "02 Controls / Buttons, fields and segments",
    classification: "CANONICAL",
    migrationStatus: "Default for new recurring fields.",
  },
  {
    family: "Form controls",
    semanticJob: "Page-local fields, selects and search controls",
    implementation: "Builder, Stamps and Map fields plus Discover, Profile and Dashboard composite controls",
    owner: "Page and composite production components",
    consumers: ["Builder", "Discover composites", "Stamps", "Map", "Profile preference controls", "Dashboard search"],
    differences: "Label placement, control height, radius, validation and focus treatment vary.",
    storybookCoverage: "06 Audit / Form-control comparison",
    classification: "DUPLICATE / MIGRATION CANDIDATE",
    migrationStatus: "Passport selectors, Discover labelled filters and Dashboard gift fields are migrated; preserve the keyboard contracts of remaining composite controls.",
  },
  {
    family: "Segmented controls",
    semanticJob: "Switch one compact view or filter in place",
    implementation: "EasyTSegmentedControl",
    owner: "components/easyt/easyt-controls.tsx",
    consumers: ["Dashboard", "Compact filtered views"],
    differences: "Pressed state, accessible group naming, optional counts and narrow layout share one owner.",
    storybookCoverage: "02 Controls / Buttons, fields and segments / Segmented",
    classification: "CANONICAL",
    migrationStatus: "Use for in-place mutually exclusive view selection; do not substitute it for navigation.",
  },
  {
    family: "Boolean controls",
    semanticJob: "Capture an independent yes/no preference or specialised radio answer",
    implementation: "Privacy preference checkboxes, admin publication controls and Builder answer composites",
    owner: "Their legal, administrative or Builder form owner",
    consumers: ["Cookie preferences", "Route administration", "Builder clarification"],
    differences: "These controls have distinct legal, administrative and guided-question contracts; no generic Morrovia checkbox/radio owner exists today.",
    storybookCoverage: "03 Status & Feedback / Privacy choices; 05 Product Patterns / Builder review",
    classification: "INTENTIONAL EXCEPTION",
    migrationStatus: "Keep the current semantic owners; create a shared boolean-control owner only after a traveller-facing pattern genuinely recurs.",
    canonicalReference: "Form controls — EasyT field family for labelled text/select/textarea jobs; Segmented controls for in-place view selection",
  },
  {
    family: "Date & quantity controls",
    semanticJob: "Date/range selection and bounded traveller counts",
    implementation: "MorroviaDatePicker and MorroviaQuantitySelector",
    owner: "components/easyt/morrovia-date-picker.tsx and morrovia-quantity-selector.tsx",
    consumers: ["Builder and booking flows"],
    differences: "Own keyboard, compact and mobile behavior.",
    storybookCoverage: "02 Controls / Date, quantity and forms",
    classification: "CANONICAL",
    migrationStatus: "Stable source of truth.",
  },
  {
    family: "Contextual disclosure",
    semanticJob: "Explain AI, privacy, provider or product context beside the affected action",
    implementation: "MorroviaContextualDisclosure",
    owner: "components/easyt/morrovia-feedback.tsx",
    consumers: ["Luna/AI transparency", "Provider and privacy context", "Compact help"],
    differences: "Non-modal dialog semantics, expanded state, Escape/outside close and focus return are shared.",
    storybookCoverage: "03 Status & Feedback / Confirmation and recovery / Contextual transparency disclosure",
    classification: "CANONICAL",
    migrationStatus: "Stable source of truth for contextual non-modal disclosure.",
  },
  {
    family: "Privacy choices",
    semanticJob: "Collect and revise analytics and affiliate-tracking consent",
    implementation: "PrivacyConsent and CookiePreferences",
    owner: "components/privacy-consent.tsx, components/cookie-preferences.tsx and lib/privacy-consent.ts",
    consumers: ["Journey shell", "Cookie settings"],
    differences: "The presentation and stored consent semantics are covered together.",
    storybookCoverage: "03 Status & Feedback / Privacy choices",
    classification: "CANONICAL",
    migrationStatus: "Stable legal-choice owner.",
  },
  {
    family: "Legal disclosures",
    semanticJob: "Present durable privacy, cookie and affiliate information",
    implementation: "Privacy, cookie and affiliate-disclosure editorial pages",
    owner: "Their public page owner with MorroviaLegalIdentity and MorroviaFooter",
    consumers: ["Privacy", "Cookies", "Affiliate disclosure"],
    differences: "Required content, anchors and runtime controls differ; these are editorial pages rather than one reusable panel.",
    storybookCoverage: "03 Status & Feedback / Privacy choices; 06 Audit / Intentional exceptions",
    classification: "INTENTIONAL EXCEPTION",
    migrationStatus: "Keep page-owned content and reuse the legal identity, footer, tokens and contextual disclosure owner where their jobs match.",
    canonicalReference: "Layout — editorial page archetype; Privacy choices and Contextual disclosure — canonical interactive owners",
  },
  {
    family: "Status & feedback",
    semanticJob: "Save, persistent status, recovery and consequential confirmation",
    implementation: "MorroviaSaveStatus, MorroviaStatusBanner, MorroviaRecoveryFeedback and MorroviaConfirmationDialog",
    owner: "components/easyt/morrovia-feedback.tsx",
    consumers: ["Dashboard", "TripShell", "Trip mode", "Builder save flows"],
    differences: "Roles, live regions, focus return and safety copy are shared.",
    storybookCoverage: "03 Status & Feedback / Confirmation and recovery",
    classification: "CANONICAL",
    migrationStatus: "Stable source of truth.",
  },
  {
    family: "Status & feedback",
    semanticJob: "Domain-specific health, timing, booking and readiness state",
    implementation: "Trip Health, Builder timing warnings, preparation tasks and booking state",
    owner: "Their product-pattern components",
    consumers: ["Builder", "Overview", "Itinerary", "Map"],
    differences: "These states carry domain data and cannot be reduced to generic banners or chips.",
    storybookCoverage: "03 Status & Feedback / Status catalogue and 05 Product Patterns",
    classification: "INTENTIONAL EXCEPTION",
    migrationStatus: "Preserve domain semantics while reusing foundation tokens.",
    canonicalReference: "Status & feedback — MorroviaStatusBanner and the shared feedback family",
  },
  {
    family: "Status chips",
    semanticJob: "Compact completion, booking and suggestion labels",
    implementation: "Preparation, itinerary, passport, dashboard and booking-local chips",
    owner: "Product-pattern CSS modules",
    consumers: ["Overview", "Itinerary", "Passport", "Dashboard", "Map"],
    differences: "The labels share compact metadata styling but encode different state machines.",
    storybookCoverage: "03 Status & Feedback / Status catalogue and 06 Audit / Status comparison",
    classification: "INTENTIONAL EXCEPTION",
    migrationStatus: "Keep state-machine ownership local; revisit only if the underlying taxonomy converges.",
    canonicalReference: "Status & feedback — shared feedback components for generic product truth",
  },
  {
    family: "Loading & progress",
    semanticJob: "Skeletons, long waits, staged planning, retry and map loading",
    implementation: "MorroviaSkeleton, MorroviaSectionStatus, MorroviaPlanningProgress and MorroviaMapLoading",
    owner: "components/easyt/morrovia-loading-states.tsx",
    consumers: ["Builder", "Map", "Async sections", "Route planning"],
    differences: "Loading remains local to the affected surface and preserves current context.",
    storybookCoverage: "03 Status & Feedback / Loading and progress",
    classification: "CANONICAL",
    migrationStatus: "Stable source of truth.",
  },
  {
    family: "Navigation",
    semanticJob: "Global desktop navigation and mobile dock",
    implementation: "EasyTNavigation",
    owner: "app/journey/easyt-navigation.tsx",
    consumers: ["All Journey pages"],
    differences: "Desktop header, compact menu and mobile dock are one responsive owner.",
    storybookCoverage: "04 Structure / Global navigation",
    classification: "CANONICAL",
    migrationStatus: "Stable source of truth.",
  },
  {
    family: "Navigation",
    semanticJob: "Trip-local workspace switching",
    implementation: "TripShellNavigation",
    owner: "components/easyt/trip-shell-client.tsx",
    consumers: ["Overview", "Map", "Itinerary"],
    differences: "A three-workspace subnavigation, not a second global nav.",
    storybookCoverage: "04 Structure / Trip shell",
    classification: "INTENTIONAL EXCEPTION",
    migrationStatus: "Semantically distinct and canonical within TripShell.",
    canonicalReference: "Navigation — EasyTNavigation global desktop, compact and mobile owner",
  },
  {
    family: "Cards & panels",
    semanticJob: "Group related product information and actions",
    implementation: "Route, trip, stay, task, passport, map and recommendation cards",
    owner: "Each production pattern",
    consumers: ["Routes", "Dashboard", "Overview", "Itinerary", "Map", "Passport"],
    differences: "Anatomy, density, imagery, action priority and responsive behavior materially differ.",
    storybookCoverage: "05 Product Patterns and 06 Audit / Card comparison",
    classification: "INTENTIONAL EXCEPTION",
    migrationStatus: "No universal card primitive by design.",
    canonicalReference: "Cards & panels — product-pattern ownership with shared foundations (no universal Card)",
  },
  {
    family: "Section headers",
    semanticJob: "Name a page region and expose contextual actions",
    implementation: "Page-local heading compositions",
    owner: "Homepage, Overview, Itinerary, Routes, Dashboard and account CSS",
    consumers: ["Most composed pages"],
    differences: "Shared typography roles but different action, summary and responsive contracts.",
    storybookCoverage: "06 Audit / Typography and card comparisons",
    classification: "INTENTIONAL EXCEPTION",
    migrationStatus: "Keep composition with each page archetype; reuse the canonical typography roles.",
    canonicalReference: "Typography and page archetypes — shared family roles with product-owned composition",
  },
  {
    family: "Trip capture",
    semanticJob: "Capture a natural-language trip idea with voice support",
    implementation: "MorroviaTripCapture",
    owner: "components/easyt/morrovia-trip-capture.tsx",
    consumers: ["Homepage", "Builder handoff"],
    differences: "Page owners compose context; the text-plus-voice core is shared.",
    storybookCoverage: "05 Product Patterns / Trip capture",
    classification: "CANONICAL",
    migrationStatus: "Stable shared core.",
  },
  {
    family: "Trip shell",
    semanticJob: "Trip identity, metadata and workspace navigation",
    implementation: "TripShell",
    owner: "components/easyt/trip-shell.tsx",
    consumers: ["Overview", "Map", "Itinerary"],
    differences: "One shared trip header; each workspace owns only its content region.",
    storybookCoverage: "04 Structure / Trip shell",
    classification: "CANONICAL",
    migrationStatus: "Stable source of truth.",
  },
  {
    family: "Overview patterns",
    semanticJob: "Next action, health, readiness, preparation and route context",
    implementation: "TripOverviewWorkspace and TripPreparationTaskSection",
    owner: "components/easyt/trip-overview-workspace.tsx and trip-preparation.tsx",
    consumers: ["Trip Overview"],
    differences: "Truthful projections over canonical trip data; Prep is not a second workspace.",
    storybookCoverage: "05 Product Patterns / Trip workspace / Overview",
    classification: "CANONICAL",
    migrationStatus: "Stable source of truth.",
  },
  {
    family: "Itinerary patterns",
    semanticJob: "Day selection, timeline rows, insertion, direct editing and contextual rail",
    implementation: "TripItineraryWorkspace",
    owner: "components/easyt/trip-itinerary-workspace.tsx",
    consumers: ["Trip Itinerary"],
    differences: "Composed interaction with canonical mutation and persistence paths.",
    storybookCoverage: "05 Product Patterns / Trip workspace / Itinerary",
    classification: "CANONICAL",
    migrationStatus: "Stable source of truth.",
  },
  {
    family: "Map patterns",
    semanticJob: "Route canvas, stop/place selection, overlays and spatial actions",
    implementation: "TripMapWorkspace and JourneyPlannerMap",
    owner: "components/easyt/trip-map-workspace.tsx and components/journey-planner-map.tsx",
    consumers: ["Trip Map", "Overview preview", "Itinerary day preview"],
    differences: "Full and preview modes are explicitly scoped; the main Map retains its defaults.",
    storybookCoverage: "05 Product Patterns / Trip workspace / Map",
    classification: "CANONICAL",
    migrationStatus: "Stable source of truth.",
  },
  {
    family: "Route discovery",
    semanticJob: "Browse routes, compare route cards and inspect a route detail",
    implementation: "DiscoveryBrowser and RouteDetailView",
    owner: "app/journey/discover and app/journey/routes/[slug]",
    consumers: ["Routes", "Route detail"],
    differences: "Editorial discovery uses image-led cards; route detail adds sequenced planning context.",
    storybookCoverage: "05 Product Patterns / Routes",
    classification: "CANONICAL",
    migrationStatus: "Product-specific canonical patterns.",
  },
  {
    family: "AI / Copilot",
    semanticJob: "Contextual questions, proposed changes and explicit apply",
    implementation: "EasyTTripCopilot",
    owner: "components/easyt/easyt-trip-copilot.tsx",
    consumers: ["Builder", "Map", "Itinerary context"],
    differences: "Read-only answers and reviewed mutation previews share one owner.",
    storybookCoverage: "05 Product Patterns / AI and Copilot",
    classification: "CANONICAL",
    migrationStatus: "Stable source of truth.",
  },
  {
    family: "Tour and overlays",
    semanticJob: "First-visit guidance and focus-managed product orientation",
    implementation: "EasyTProductTour",
    owner: "components/easyt/easyt-product-tour.tsx",
    consumers: ["Global navigation", "First visit"],
    differences: "Image-led, multi-step and focus-trapped; not interchangeable with consequential confirmation.",
    storybookCoverage: "04 Structure / Dialogs and overlays",
    classification: "INTENTIONAL EXCEPTION",
    migrationStatus: "Purposefully distinct from confirmation dialogs.",
    canonicalReference: "Status & feedback — MorroviaConfirmationDialog for consequential confirmation",
  },
  {
    family: "Personal libraries",
    semanticJob: "Trips and visited/want-to-visit collections",
    implementation: "DashboardClient and StampedExperience",
    owner: "app/journey/dashboard and app/journey/stamped",
    consumers: ["Trips", "Stamps"],
    differences: "Both are libraries, but trip continuation and map-based memory browsing have different interaction models.",
    storybookCoverage: "05 Product Patterns / Trips dashboard and Stamps",
    classification: "INTENTIONAL EXCEPTION",
    migrationStatus: "Share foundations, not layouts.",
    canonicalReference: "Layout and Cards & panels — shared foundations with product-pattern owners",
  },
  {
    family: "Passport",
    semanticJob: "Public entry-requirement check and trust context",
    implementation: "PassportDestinationClient",
    owner: "app/journey/passport/passport-destination-client.tsx",
    consumers: ["Passport"],
    differences: "A focused public workflow with provider result, provenance and privacy states.",
    storybookCoverage: "05 Product Patterns / Passport",
    classification: "INTENTIONAL EXCEPTION",
    migrationStatus: "Unique product flow; keep page-owned while documenting states.",
    canonicalReference: "Form controls and Status & feedback — EasyT controls and Morrovia feedback families",
  },
  {
    family: "Footer",
    semanticJob: "Canonical public product footer",
    implementation: "MorroviaFooter",
    owner: "components/morrovia-footer.tsx",
    consumers: ["Homepage and public editorial surfaces"],
    differences: "One production component.",
    storybookCoverage: "04 Structure / Footer",
    classification: "CANONICAL",
    migrationStatus: "Stable source of truth.",
  },
];

export function visualAuditSummary(records = visualAuditRecords) {
  const counts = records.reduce<Record<VisualAuditClassification, number>>((current, record) => {
    current[record.classification] += 1;
    return current;
  }, {
    CANONICAL: 0,
    "DUPLICATE / MIGRATION CANDIDATE": 0,
    "INTENTIONAL EXCEPTION": 0,
    UNDECIDED: 0,
  });
  const families = new Set(records.map((record) => record.family));
  const duplicateFamilies = new Set(records.filter((record) => record.classification === "DUPLICATE / MIGRATION CANDIDATE").map((record) => record.family));
  return { records: records.length, families: families.size, duplicateFamilies: duplicateFamilies.size, counts };
}
