import type { RouteConnection, RouteFamily, RouteFamilyStop } from "./route-catalog.ts";

const reviewedAt = "2026-09-10";
const verify = "Confirm the dated connection, border requirements and door-to-door plan before booking.";

const stop = (
  name: string,
  country: string,
  coordinates: [number, number],
  minimumNights: number,
  recommendedNights: number,
  reason: string,
  nightGuidanceRationale: string,
): RouteFamilyStop => ({ name, country, coordinates, minimumNights, recommendedNights, reason, nightGuidanceRationale });

const connection = (
  from: string,
  to: string,
  mode: RouteConnection["mode"],
  note: string,
): RouteConnection => ({ from, to, mode, planningMinutes: null, note: `${note} ${verify}`, confidence: "needs-review" });

const source = (label: string, url: string, covers: string, owner: string) => ({
  label,
  url,
  covers,
  owner,
  checkedAt: reviewedAt,
  limitations: "Official destination and route context; not live schedules, border advice, availability or a personalised journey time.",
});

type FeaturedRouteInput = Omit<RouteFamily, "confidence" | "reviewedAt" | "release"> & {
  routeOrderRationale: string;
  releaseImage: NonNullable<RouteFamily["release"]>["image"];
};

function featuredRoute(input: FeaturedRouteInput): RouteFamily {
  const { routeOrderRationale, releaseImage, ...route } = input;
  return {
    ...route,
    confidence: "medium",
    reviewedAt,
    release: {
      routeOrderRationale,
      editorialOwner: "Codex — route research and content preparation",
      editorialReviewer: "Shaun Whiting",
      explicitUnknowns: route.connections.map((item) => ({
        kind: "connection",
        reference: `${item.from} → ${item.to}`,
        reason: item.note,
      })),
      image: releaseImage,
    },
  };
}

/**
 * Reviewed, publishable route families used by Discover, Route Detail, the
 * homepage collection and Builder handoff. These are canonical route records,
 * not homepage-only presentation data.
 */
export const featuredRouteFamilies: RouteFamily[] = [
  featuredRoute({
    key: "japan-south-korea",
    title: "Japan + South Korea",
    region: "asia",
    countries: ["Japan", "South Korea"],
    interests: ["rail", "culture", "food"],
    bestFor: "A rail-led route through Japanese cities and mountain towns, followed by a deliberate international connection and a fast Korean rail finish.",
    character: "Rail + international connection",
    suggestedDays: { min: 16, ideal: 19, max: 22 },
    bases: ["Tokyo", "Kanazawa", "Takayama", "Kyoto", "Osaka", "Seoul", "Busan"],
    stops: [
      stop("Tokyo", "Japan", [139.6917, 35.6895], 2, 3, "Arrive into a large city with time to recover and explore separate neighbourhoods.", "Three nights protect arrival recovery and one full city day."),
      stop("Kanazawa", "Japan", [136.6562, 36.5613], 1, 2, "A compact cultural base on the way toward the Japanese Alps.", "Two nights leave one unhurried day between travel days."),
      stop("Takayama", "Japan", [137.2523, 36.146], 1, 2, "A smaller mountain base that changes the rhythm between cities.", "Two nights avoid treating the mountain chapter as a transfer stop."),
      stop("Kyoto", "Japan", [135.7681, 35.0116], 3, 4, "A longer cultural chapter for neighbourhoods and separate temple days.", "Four nights protect several full days without stacking distant areas."),
      stop("Osaka", "Japan", [135.5023, 34.6937], 1, 2, "A food-led city pause before the international connection.", "Two nights create a buffer before leaving Japan."),
      stop("Seoul", "South Korea", [126.978, 37.5665], 3, 3, "A substantial first Korean base after the international transfer.", "Three nights leave two full city days after arrival."),
      stop("Busan", "South Korea", [129.0756, 35.1796], 2, 2, "A coastal Korean finish connected by intercity rail.", "Two nights leave one full coastal city day before departure."),
    ],
    connections: [
      connection("Tokyo", "Kanazawa", "train", "Rail is the broad planning mode; service and reservation details remain date-dependent."),
      connection("Kanazawa", "Takayama", "train", "Rail via Toyama or a road alternative may be better for the chosen date."),
      connection("Takayama", "Kyoto", "train", "Rail is the broad planning mode and may involve a change."),
      connection("Kyoto", "Osaka", "train", "Frequent regional rail is the broad planning mode."),
      connection("Osaka", "Seoul", "flight", "This is an international air connection with airport access and border time, not a promised direct schedule."),
      connection("Seoul", "Busan", "train", "Intercity rail is the broad planning mode."),
    ],
    seasonalNotes: ["Spring and autumn need earlier accommodation planning.", "International entry requirements and transport reservations must be checked for the travel dates."],
    highlights: ["Tokyo neighbourhoods", "Japanese Alps mountain towns", "Kyoto cultural districts", "Seoul neighbourhoods", "Busan coast"],
    sourceLinks: [
      source("Japan regional route", "https://www.japan.travel/en/au/guide/guide-takayama-shirakawa-go-kanazawa/", "Japan route context around Kanazawa and Takayama.", "Japan National Tourism Organization"),
      source("JR West journey planning", "https://www.westjr.co.jp/global/en/", "Rail network context for western Japan.", "West Japan Railway Company"),
      source("Korea destination planning", "https://english.visitkorea.or.kr/svc/main/index.do", "Official context for Seoul, Busan and travel within South Korea.", "Korea Tourism Organization"),
    ],
    imageQuery: "Japan South Korea rail mountain city journey",
    routeOrderRationale: "The sequence moves through Japan without backtracking, places the international connection after Osaka, then uses Korea's north-to-south rail corridor.",
    releaseImage: { asset: "/journey/immersive/place-kyoto-1536.webp", rights: "licensed", attribution: "Kanchi1979 · CC BY-SA 4.0 · resized and converted to WebP; display crop.", sourceUrl: "https://commons.wikimedia.org/wiki/File:JP-Kyoto-Gion-Area-Street-Night-View.jpg" },
  }),
  featuredRoute({
    key: "iceland-ring-road",
    title: "Iceland Ring Road",
    region: "europe",
    countries: ["Iceland"],
    interests: ["nature", "hiking"],
    bestFor: "A complete self-drive circuit with many overnight bases, variable road conditions and enough time to keep long landscape days realistic.",
    character: "Self-drive + circular pacing",
    suggestedDays: { min: 12, ideal: 15, max: 16 },
    bases: ["Reykjavík", "Grundarfjörður", "Akureyri", "Reykjahlíð", "Egilsstaðir", "Höfn", "Vík", "Reykjavík"],
    stops: [
      stop("Reykjavík", "Iceland", [-21.9426, 64.1466], 1, 2, "A practical arrival base before collecting the car and starting the circuit.", "Two nights protect arrival recovery and rental collection."),
      stop("Grundarfjörður", "Iceland", [-23.2647, 64.9243], 1, 2, "A practical Snæfellsnes base that adds coastal landscapes without treating the peninsula as a rushed day trip.", "Two nights allow a weather-flexible peninsula day."),
      stop("Akureyri", "Iceland", [-18.0907, 65.6885], 1, 2, "A northern city base before the Mývatn landscape chapter.", "Two nights keep the north from becoming continuous driving."),
      stop("Reykjahlíð", "Iceland", [-16.9123, 65.6421], 2, 2, "The practical overnight base for Mývatn and its volcanic landscape.", "Two nights protect one full local landscape day."),
      stop("Egilsstaðir", "Iceland", [-14.3948, 65.2601], 1, 2, "An Eastfjords base that breaks the long drive south.", "Two nights add weather and road-condition resilience."),
      stop("Höfn", "Iceland", [-15.2082, 64.2539], 1, 2, "The canonical overnight base for the Jökulsárlón southeast chapter.", "Two nights leave room for Jökulsárlón without assigning a night to the landmark itself."),
      stop("Vík", "Iceland", [-19.0083, 63.4189], 1, 2, "A south-coast base before completing the loop.", "Two nights protect a full south-coast day."),
      stop("Reykjavík", "Iceland", [-21.9426, 64.1466], 1, 1, "Return the car and finish the circular route where it began.", "One final night protects the return and onward departure."),
    ],
    connections: [
      connection("Reykjavík", "Grundarfjörður", "road", "Self-drive is the route assumption; weather and daylight shape the Snæfellsnes day."),
      connection("Grundarfjörður", "Akureyri", "road", "This is a substantial driving day and needs a rest-stop and weather plan."),
      connection("Akureyri", "Reykjahlíð", "road", "Self-drive is the route assumption for the Mývatn chapter."),
      connection("Reykjahlíð", "Egilsstaðir", "road", "This is a longer regional driving day with weather-sensitive roads."),
      connection("Egilsstaðir", "Höfn", "road", "The exact Eastfjords route and conditions change the driving allowance."),
      connection("Höfn", "Vík", "road", "Self-drive is the route assumption with Jökulsárlón and south-coast stops shaping the day."),
      connection("Vík", "Reykjavík", "road", "Self-drive completes the circuit."),
    ],
    seasonalNotes: ["Road and weather conditions can change quickly; keep each driving day flexible.", "Winter daylight and closures materially change the viability of the full circuit."],
    highlights: ["Snæfellsnes coast", "Mývatn volcanic landscapes", "Eastfjords", "Jökulsárlón from Höfn", "South coast"],
    visitIntents: [
      { name: "Snæfellsnes", base: "Grundarfjörður" },
      { name: "Mývatn", base: "Reykjahlíð" },
      { name: "Eastfjords", base: "Egilsstaðir" },
      { name: "Jökulsárlón", base: "Höfn" },
    ],
    sourceLinks: [
      source("Iceland road conditions", "https://umferdin.is/en", "Official road condition and closure context.", "Icelandic Road and Coastal Administration"),
      source("Visit Iceland", "https://www.visiticeland.com/", "Official destination context for the full circuit.", "Visit Iceland"),
    ],
    imageQuery: "Iceland Ring Road Jokulsarlon landscape self drive",
    routeOrderRationale: "The route forms a complete clockwise circuit, uses Grundarfjörður for Snæfellsnes, Reykjahlíð for Mývatn, Egilsstaðir for the Eastfjords and Höfn for Jökulsárlón.",
    releaseImage: { asset: "/journey/immersive/moment-glacier-lagoon-1536.webp", rights: "licensed", attribution: "Eric Kilby · CC BY-SA 2.0 · resized and converted to WebP; display crop.", sourceUrl: "https://commons.wikimedia.org/wiki/File:Glacier_Lagoon_-_Pano.jpg" },
  }),
  featuredRoute({
    key: "balkans-overland",
    title: "The Balkans",
    region: "europe",
    countries: ["Croatia", "Montenegro", "Albania", "North Macedonia"],
    interests: ["culture", "coast", "heritage"],
    bestFor: "A four-country overland route where border crossings, ground connections and route order matter as much as the stops themselves.",
    character: "Borders + ground connections",
    suggestedDays: { min: 12, ideal: 15, max: 18 },
    bases: ["Split", "Dubrovnik", "Kotor", "Shkodër", "Tirana", "Ohrid"],
    stops: [
      stop("Split", "Croatia", [16.4402, 43.5081], 2, 2, "An Adriatic opening with time for the old city before moving south.", "Two nights leave one full day after arrival."),
      stop("Dubrovnik", "Croatia", [18.0944, 42.6507], 2, 3, "A substantial coastal base before the first border crossing.", "Three nights protect a full old-city day and some coastal time."),
      stop("Kotor", "Montenegro", [18.7712, 42.4247], 2, 3, "A slower bay chapter between international ground transfers.", "Three nights avoid reducing the bay to an arrival and departure."),
      stop("Shkodër", "Albania", [19.5126, 42.0683], 1, 2, "A northern Albanian base that keeps the overland sequence coherent.", "Two nights leave one full local day or recovery after the border."),
      stop("Tirana", "Albania", [19.8187, 41.3275], 2, 2, "A capital-city pause before turning east toward Ohrid.", "Two nights protect one full city day."),
      stop("Ohrid", "North Macedonia", [20.8016, 41.1172], 2, 2, "A lake-side finish after the final border crossing.", "Two nights leave one full lake and old-town day."),
    ],
    connections: [
      connection("Split", "Dubrovnik", "bus", "Scheduled coach or a road transfer is the broad planning assumption."),
      connection("Dubrovnik", "Kotor", "bus", "International ground transport is the broad planning assumption; border time varies."),
      connection("Kotor", "Shkodër", "bus", "International road travel may require a change or arranged transfer."),
      connection("Shkodër", "Tirana", "bus", "Road transport is the broad planning assumption."),
      connection("Tirana", "Ohrid", "bus", "International road travel is the broad planning assumption and may require a change."),
    ],
    seasonalNotes: ["Summer border queues and coastal traffic can lengthen ground days.", "Shoulder-season services need checking before fixing the route dates."],
    highlights: ["Split old city", "Dubrovnik walls", "Kotor Bay", "Shkodër", "Tirana", "Lake Ohrid"],
    sourceLinks: [
      source("Croatia tourism", "https://croatia.hr/en-gb", "Official destination context for Split and Dubrovnik.", "Croatian National Tourist Board"),
      source("Montenegro travel", "https://www.montenegro.travel/en", "Official destination context for Kotor.", "National Tourism Organisation of Montenegro"),
      source("Albania tourism", "https://akt.gov.al/en/", "Official destination context for Shkodër and Tirana.", "Albanian National Tourism Agency"),
      source("North Macedonia tourism", "https://tourismmacedonia.gov.mk/", "Official destination context for Ohrid.", "North Macedonia tourism authority"),
    ],
    imageQuery: "Kotor Bay Adriatic mountains Balkans overland",
    routeOrderRationale: "The route follows the Adriatic south through Croatia and Montenegro, then continues through northern Albania and Tirana before the final eastbound crossing to Ohrid.",
    releaseImage: { asset: "/journey/immersive/place-kotor-1536.webp", rights: "licensed", attribution: "User:Ggia · CC BY-SA 3.0 · resized and converted to WebP; display crop.", sourceUrl: "https://commons.wikimedia.org/wiki/File:20090719_Crkva_Gospa_od_Zdravlja_Kotor_Bay_Montenegro.jpg" },
  }),
  featuredRoute({
    key: "vietnam-cambodia",
    title: "Vietnam + Cambodia",
    region: "asia",
    countries: ["Vietnam", "Cambodia"],
    interests: ["food", "culture", "nature"],
    bestFor: "A long north-to-south journey with seven meaningful bases, mixed transport choices and an international overland chapter into Cambodia.",
    character: "Distance + mixed transfers",
    suggestedDays: { min: 17, ideal: 20, max: 24 },
    bases: ["Hanoi", "Ninh Bình", "Huế", "Hội An", "Ho Chi Minh City", "Phnom Penh", "Siem Reap"],
    stops: [
      stop("Hanoi", "Vietnam", [105.8342, 21.0278], 2, 3, "A food-led arrival base before the route moves south.", "Three nights protect arrival recovery and one full city day."),
      stop("Ninh Bình", "Vietnam", [105.9745, 20.2506], 2, 2, "A landscape base for Tràng An rather than a rushed excursion.", "Two nights leave one complete landscape day."),
      stop("Huế", "Vietnam", [107.5909, 16.4637], 2, 2, "A heritage stop that gives central Vietnam its own chapter.", "Two nights protect one full heritage day."),
      stop("Hội An", "Vietnam", [108.338, 15.8801], 2, 3, "A slower central base before the long move south.", "Three nights create room for old-town, food and coastal time."),
      stop("Ho Chi Minh City", "Vietnam", [106.6297, 10.8231], 3, 3, "A substantial southern city base before crossing into Cambodia.", "Three nights leave two full city days after arrival."),
      stop("Phnom Penh", "Cambodia", [104.9282, 11.5564], 2, 2, "A distinct capital chapter after the international border.", "Two nights protect one full city day."),
      stop("Siem Reap", "Cambodia", [103.8552, 13.3633], 3, 3, "The practical base for separate Angkor temple days.", "Three nights keep Angkor from becoming one compressed day."),
    ],
    connections: [
      connection("Hanoi", "Ninh Bình", "train", "Rail or road can support this regional move."),
      connection("Ninh Bình", "Huế", "train", "Long-distance rail is the broad planning mode; an overnight service changes usable time."),
      connection("Huế", "Hội An", "road", "Road transport across central Vietnam is the broad planning mode."),
      connection("Hội An", "Ho Chi Minh City", "flight", "This is an air-plus-road planning connection through a regional airport, not a promised city-centre direct service."),
      connection("Ho Chi Minh City", "Phnom Penh", "bus", "International road transport is the broad planning mode and border time varies."),
      connection("Phnom Penh", "Siem Reap", "bus", "Scheduled road transport is the broad planning mode."),
    ],
    seasonalNotes: ["Weather differs materially between northern, central and southern Vietnam.", "International border rules and service times need checking for the chosen dates."],
    highlights: ["Hanoi food neighbourhoods", "Tràng An from Ninh Bình", "Huế heritage", "Hội An", "Phnom Penh", "Angkor from Siem Reap"],
    visitIntents: [
      { name: "Tràng An", base: "Ninh Bình" },
      { name: "Angkor Wat", base: "Siem Reap" },
    ],
    sourceLinks: [
      source("Vietnam tourism", "https://vietnam.travel/", "Official destination context across Vietnam.", "Vietnam National Authority of Tourism"),
      source("Cambodia tourism", "https://www.tourismcambodia.org/", "Official destination context for Phnom Penh and Siem Reap.", "Ministry of Tourism, Cambodia"),
    ],
    imageQuery: "Trang An Vietnam Cambodia long route landscape",
    routeOrderRationale: "The sequence moves south through Vietnam without backtracking, keeps Ninh Bình and Huế as real bases, then crosses into Cambodia for Phnom Penh before finishing at Siem Reap.",
    releaseImage: { asset: "/journey/immersive/moment-angkor-wat-1536.webp", rights: "licensed", attribution: "Satdeep Gill · CC BY-SA 4.0 · resized and converted to WebP; display crop.", sourceUrl: "https://commons.wikimedia.org/wiki/File:Angkor_Wat_with_its_reflection.jpg" },
  }),
  featuredRoute({
    key: "namibia-self-drive",
    title: "Namibia Self-Drive",
    region: "africa",
    countries: ["Namibia"],
    interests: ["nature", "wildlife", "hiking"],
    bestFor: "A remote circular self-drive where gravel roads, fuel, daylight and realistic nights shape the journey.",
    character: "Remote self-drive + circular route",
    suggestedDays: { min: 12, ideal: 14, max: 16 },
    bases: ["Windhoek", "Sossusvlei", "Swakopmund", "Damaraland", "Etosha", "Waterberg", "Windhoek"],
    stops: [
      stop("Windhoek", "Namibia", [17.0832, -22.5609], 1, 1, "A practical arrival base for vehicle collection and supplies.", "One night avoids starting a remote drive immediately after arrival."),
      stop("Sossusvlei", "Namibia", [15.2939, -24.7588], 2, 2, "A desert base area reached by a substantial road day.", "Two nights leave one full early-start landscape day."),
      stop("Swakopmund", "Namibia", [14.5053, -22.6784], 2, 2, "A coastal pause between remote road chapters.", "Two nights create a recovery day after gravel-road travel."),
      stop("Damaraland", "Namibia", [14.5, -20.5], 1, 2, "A flexible regional base that breaks the route toward Etosha.", "Two nights allow for the exact lodge location and a local landscape day."),
      stop("Etosha", "Namibia", [16.325, -18.8556], 3, 3, "A multi-night wildlife chapter where the exact gate and camp matter.", "Three nights protect two wildlife days and internal park movement."),
      stop("Waterberg", "Namibia", [17.245, -20.453], 1, 2, "A final landscape stop that breaks the return to Windhoek.", "Two nights prevent the final region becoming only a transit stop."),
      stop("Windhoek", "Namibia", [17.0832, -22.5609], 1, 1, "Return the vehicle and finish the circular route.", "One final night protects vehicle return and onward departure."),
    ],
    connections: [
      connection("Windhoek", "Sossusvlei", "road", "Remote self-drive is the route assumption; road surface and the exact lodge location matter."),
      connection("Sossusvlei", "Swakopmund", "road", "Remote self-drive is the route assumption with limited services between bases."),
      connection("Swakopmund", "Damaraland", "road", "The exact Damaraland base materially changes the road day."),
      connection("Damaraland", "Etosha", "road", "The exact Etosha gate and camp materially change the road day."),
      connection("Etosha", "Waterberg", "road", "Self-drive is the route assumption and internal park movement must be kept separate."),
      connection("Waterberg", "Windhoek", "road", "Self-drive completes the circuit."),
    ],
    seasonalNotes: ["Avoid night driving and check road, fuel and tyre guidance with the rental provider.", "Park gates, water, fuel and accommodation availability need advance confirmation."],
    highlights: ["Sossusvlei dunes", "Atlantic coast", "Damaraland landscapes", "Etosha wildlife", "Waterberg"],
    sourceLinks: [
      source("Visit Namibia planning guides", "https://visitnamibia.com.na/travel-planning-guides/", "Official national self-drive and destination planning context.", "Namibia Tourism Board"),
      source("Namibia road authority", "https://www.ra.org.na/", "Official national road authority context.", "Roads Authority Namibia"),
    ],
    imageQuery: "Sossusvlei Namibia desert road self drive",
    routeOrderRationale: "The circuit moves southwest to the Namib, north along the coast and through Damaraland to Etosha, then breaks the return at Waterberg before closing in Windhoek.",
    releaseImage: { asset: "/journey/immersive/moment-sossusvlei-1536.webp", rights: "licensed", attribution: "Diego Delso · CC BY-SA 4.0 · resized and converted to WebP; display crop.", sourceUrl: "https://commons.wikimedia.org/wiki/File:Sossusvlei,_Namibia,_2018-08-06,_DD_040.jpg" },
  }),
  featuredRoute({
    key: "peru-bolivia",
    title: "Peru + Bolivia",
    region: "south-america",
    countries: ["Peru", "Bolivia"],
    interests: ["nature", "culture", "heritage"],
    bestFor: "An altitude-aware route with long distances, mixed transfer modes and Puno as the real overnight base for Lake Titicaca.",
    character: "Altitude + mixed transfers",
    suggestedDays: { min: 16, ideal: 19, max: 23 },
    bases: ["Lima", "Huacachina", "Arequipa", "Cusco", "Puno", "La Paz", "Uyuni"],
    stops: [
      stop("Lima", "Peru", [-77.0428, -12.0464], 2, 3, "A low-altitude arrival base before the route turns inland.", "Three nights protect arrival recovery and one full city day."),
      stop("Huacachina", "Peru", [-75.7642, -14.0875], 1, 1, "A short desert chapter reached by road from Lima.", "One night is enough for a focused desert stop before continuing south."),
      stop("Arequipa", "Peru", [-71.5375, -16.409], 2, 2, "A city base that begins the gradual move toward higher altitude.", "Two nights protect one full city day before the next highland transfer."),
      stop("Cusco", "Peru", [-71.9785, -13.517], 3, 4, "A substantial high-altitude cultural base with recovery time.", "Four nights protect acclimatisation and separate cultural days."),
      stop("Puno", "Peru", [-70.0219, -15.84], 2, 2, "The canonical overnight base for Lake Titicaca before the border crossing.", "Two nights leave one lake-focused day without inventing a lake overnight entity."),
      stop("La Paz", "Bolivia", [-68.1193, -16.4897], 2, 3, "A high-altitude capital chapter after the international transfer.", "Three nights protect recovery and one full city day."),
      stop("Uyuni", "Bolivia", [-66.825, -20.4604], 2, 2, "The practical base for the salt-flat chapter.", "Two nights allow for a full-day excursion and transport uncertainty."),
    ],
    connections: [
      connection("Lima", "Huacachina", "road", "Road travel through the Ica region is the broad planning mode."),
      connection("Huacachina", "Arequipa", "road", "This is a long road connection and may work better with an overnight service."),
      connection("Arequipa", "Cusco", "flight", "Air or long-distance road may be appropriate; the selected option changes altitude pacing and usable time."),
      connection("Cusco", "Puno", "train", "Rail or road may be appropriate and services are not assumed to operate daily."),
      connection("Puno", "La Paz", "bus", "International road travel via the Lake Titicaca region is the broad planning mode and border time varies."),
      connection("La Paz", "Uyuni", "flight", "Air or overnight road/rail may be appropriate; no direct schedule is promised."),
    ],
    seasonalNotes: ["Altitude needs gentler arrival days in Cusco, Puno and La Paz.", "Wet-season conditions can affect Uyuni excursions and road travel."],
    highlights: ["Lima food districts", "Huacachina dunes", "Arequipa", "Cusco", "Lake Titicaca from Puno", "La Paz", "Salar de Uyuni"],
    visitIntents: [{ name: "Lake Titicaca", base: "Puno" }],
    sourceLinks: [
      source("Peru Travel", "https://www.peru.travel/en", "Official destination context for the Peruvian bases.", "PROMPERÚ"),
      source("Puno and Lake Titicaca guide", "https://www.gob.pe/institucion/mincetur/informes-publicaciones/4721585-guia-informativa-viajero-en-ruta-puno-lago-titicaca", "Official context establishing Puno as the route base for Lake Titicaca.", "Ministry of Foreign Trade and Tourism of Peru"),
      source("Bolivia travel", "https://bolivia.travel/", "Official destination context for La Paz and Uyuni.", "Bolivia travel authority"),
    ],
    imageQuery: "Salar de Uyuni Andes Peru Bolivia route",
    routeOrderRationale: "The route starts at low altitude, moves south before climbing through Arequipa and Cusco, uses Puno as the real Lake Titicaca base, then crosses into Bolivia for La Paz and Uyuni.",
    releaseImage: { asset: "/journey/immersive/moment-uyuni-1536.webp", rights: "licensed", attribution: "Diego Delso · CC BY-SA 4.0 · resized and converted to WebP; display crop.", sourceUrl: "https://commons.wikimedia.org/wiki/File:Salar_de_Uyuni,_Bolivia,_2016-02-04,_DD_10-12_HDR.JPG" },
  }),
  featuredRoute({
    key: "mexico-guatemala",
    title: "Mexico + Guatemala",
    region: "central-america",
    countries: ["Mexico", "Guatemala"],
    interests: ["culture", "heritage", "nature"],
    bestFor: "A cross-border route that distinguishes Tikal as a visit from Flores while connecting seven overnight bases across southern Mexico and Guatemala.",
    character: "Cross-border + landmark intelligence",
    suggestedDays: { min: 18, ideal: 21, max: 25 },
    bases: ["Mexico City", "Oaxaca", "San Cristóbal de las Casas", "Palenque", "Flores", "Antigua Guatemala", "Panajachel"],
    stops: [
      stop("Mexico City", "Mexico", [-99.1332, 19.4326], 3, 4, "A substantial arrival base before moving through southern Mexico.", "Four nights protect arrival recovery and separate city days."),
      stop("Oaxaca", "Mexico", [-96.7266, 17.0732], 2, 3, "A food and culture base with enough time beyond the transfer day.", "Three nights leave two full local days."),
      stop("San Cristóbal de las Casas", "Mexico", [-92.6376, 16.737], 2, 3, "A highland base that breaks the long route toward Palenque.", "Three nights protect one complete highland day and a weather buffer."),
      stop("Palenque", "Mexico", [-91.9822, 17.5095], 1, 2, "A practical base for the archaeological landscape before the border journey.", "Two nights keep the visit separate from the next international transfer."),
      stop("Flores", "Guatemala", [-89.883, 16.929], 3, 3, "The canonical overnight base for a Tikal visit.", "Three nights protect a full Tikal day without treating the landmark as a hotel base."),
      stop("Antigua Guatemala", "Guatemala", [-90.7339, 14.5586], 2, 3, "A substantial highland city base after the long move from Petén.", "Three nights protect recovery and two slower city days."),
      stop("Panajachel", "Guatemala", [-91.1565, 14.741], 2, 2, "A practical Lake Atitlán base for the final chapter.", "Two nights protect one complete lake day while keeping the overnight place explicit."),
    ],
    connections: [
      connection("Mexico City", "Oaxaca", "bus", "Long-distance road transport is the broad planning mode."),
      connection("Oaxaca", "San Cristóbal de las Casas", "bus", "This is a long road connection and may work better as an overnight service."),
      connection("San Cristóbal de las Casas", "Palenque", "road", "Road transport is the broad planning mode and mountain conditions affect the day."),
      connection("Palenque", "Flores", "bus", "International road travel is the broad planning mode and border time varies."),
      connection("Flores", "Antigua Guatemala", "flight", "This is an air-plus-road connection via Guatemala City, not a promised direct flight to Antigua."),
      connection("Antigua Guatemala", "Panajachel", "road", "Road transport is the broad planning mode; conditions and the chosen lake transfer change the final segment."),
    ],
    seasonalNotes: ["Rainy-season road conditions can affect the southern Mexico and Petén legs.", "Border requirements and the exact Lake Atitlán base need confirmation before booking."],
    highlights: ["Mexico City neighbourhoods", "Oaxaca food and culture", "Chiapas highlands", "Palenque", "Tikal visit from Flores", "Antigua Guatemala", "Lake Atitlán"],
    visitIntents: [
      { name: "Tikal", base: "Flores" },
      { name: "Lake Atitlán", base: "Panajachel" },
    ],
    sourceLinks: [
      source("Visit Mexico", "https://visitmexico.com/", "Official destination context for the Mexican bases.", "Mexico tourism authority"),
      source("Guatemala tourism", "https://inguat.gob.gt/", "Official destination context for Flores, Antigua Guatemala and Lake Atitlán.", "Guatemalan Tourism Institute"),
      source("Tikal World Heritage", "https://whc.unesco.org/en/list/64/", "Tikal's landmark identity and World Heritage context.", "UNESCO World Heritage Centre"),
    ],
    imageQuery: "Lake Atitlan Guatemala Oaxaca Chiapas route",
    routeOrderRationale: "The route moves overland through southern Mexico, crosses from Palenque to Flores, keeps Tikal as a visit from Flores, then uses an air-plus-road connection to Antigua before finishing at Panajachel on Lake Atitlán.",
    releaseImage: { asset: "/journey/immersive/moment-atitlan-1536.webp", rights: "licensed", attribution: "Diandumb13 · CC BY 4.0 · resized and converted to WebP; display crop.", sourceUrl: "https://commons.wikimedia.org/wiki/File:IMG_Lake_Atitlan,_Guatemala.jpg" },
  }),
];
